FIX_HOST=127.0.0.1
#FIX_PORT=9999
FIX_PORT=44999
STREAM_ID=1

INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608

DB_URL=jdbc:mysql://localhost:3306/trader?
DB_USER=trader
DB_PASSWORD=h5!0xhnwnu89sVD38g1
#DB_URL=jdbc:postgresql://localhost:5432/trader
#DB_USER=trader2
#DB_PASSWORD=asdhkjh1zx31

USER_LIST=chris/password,raakhee/password,steve/password
MARKET_STATUS=0