package com.solfini.integration;

import com.solfini.common.MessageType;
import com.solfini.instrument.Balance;
import com.solfini.instrument.InstrumentCache;
import com.solfini.internal.admin.schema.AssetType;
import org.junit.Test;
import com.solfini.sbe.encoder.Side;
import uk.co.real_logic.artio.fields.DecimalFloat;

import static com.solfini.common.Constants.ARRAY_ORDER_BOOK;
import static com.solfini.common.Constants.MARGIN_PREORDER_CHECK;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class AutoLiquidationWithInsuranceFundTest extends IntegrationTest {
  private static final AtomicInteger currentOrderID = new AtomicInteger();

  @Override
  public void setup() throws Exception {
    if(InstrumentCache.get(SECURITY_ID_QUOTED) == null) {
      createInstrument(SECURITY_ID_QUOTED, AssetType.ASSET, "BTC", "BTC", 0, 0,
        ARRAY_ORDER_BOOK, MARGIN_PREORDER_CHECK, 0, 0);
    }

    if(InstrumentCache.get(SECURITY_ID_QUOTE) == null) {
      createInstrument(SECURITY_ID_QUOTE, AssetType.ASSET, "USDT", "USDT", 0, 0,
        ARRAY_ORDER_BOOK, MARGIN_PREORDER_CHECK, 0, 0);
    }

    if(InstrumentCache.getPair(SECURITY_ID_PAIR) == null) {
      createInstrument(SECURITY_ID_PAIR, AssetType.PAIR, "BTC/USDT", "BTC/USDT", 0, 0,
        ARRAY_ORDER_BOOK, MARGIN_PREORDER_CHECK, SECURITY_ID_QUOTED, SECURITY_ID_QUOTE);
    }

    List<Balance> balanceListOne = createBalanceList(20_000, 20_000, 20_000);
    createNewUserWithBalance(USER_ID_FIVE, "user104", "123user104", 0, 1, false, balanceListOne);

    List<Balance> balanceListTwo = createBalanceList(40_000, 40_000, 40_000);
    createNewUserWithBalance(USER_ID_SIX, "user105", "123user105", 0, 1, false, balanceListTwo);

  }

  //@Test
  public void alDueToNegativeBalanceNoOpenOrder() throws Exception {
    publisher.send(globalStateAdminMessage(1));

    List<Balance> balanceList = createBalanceList(-50, -50, -50);
    publisher.send(balanceAdminMessage(USER_ID_ONE, 1, 1, 1, balanceList));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=50, qty_scale=0, side=BUY, orderId=1, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=0, quantityLong=50, quantityOrigLong=50, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("CancelOrder [securityId=13, price=0, side=BUY, qty=50, origOrderId=1, cancelId=1, cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=0, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=40, qty_scale=0, side=BUY, orderId=2, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=0, quantityLong=40, quantityOrigLong=40, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");


    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=40, qty_scale=0, side=SELL, orderId=3, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[0], ordType=LIMIT, type=1, priceInt=0, quantityLong=40, quantityOrigLong=40, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

//    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=BUY, ordType=LIMIT, account=[1, 0, 0], orderId=2, secondaryOrderId=0, execId=1, secondaryExecId=1, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=1, isPaidToInsurance=true, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=SELL, ordType=LIMIT, account=[0], orderId=3, secondaryOrderId=0, execId=1, secondaryExecId=1, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=0, isPaidToInsurance=false, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=4, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=0, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=SELL, orderId=5, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[0], ordType=LIMIT, type=1, priceInt=0, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=BUY, ordType=LIMIT, account=[1, 0, 0], orderId=4, secondaryOrderId=0, execId=2, secondaryExecId=2, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=1, isPaidToInsurance=true, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=SELL, ordType=LIMIT, account=[0], orderId=5, secondaryOrderId=0, execId=2, secondaryExecId=2, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=0, isPaidToInsurance=false, execType=CALCULATED, ordStatus=null]");
  }

  //@Test
  public void alDueToNegativeBalanceWhenOpenOrderByLiquidizedUser() throws Exception {
    publisher.send(order(1, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(10, 0), Side.BUY, USER_ID_ONE, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=1, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    publisher.send(globalStateAdminMessage(1));

    List<Balance> balanceList = createBalanceList(-50, -50, -50);
    publisher.send(balanceAdminMessage(USER_ID_ONE, 1, 1, 1, balanceList));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-5.0, usdUnrealized=-5.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=50, qty_scale=0, side=BUY, orderId=2, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=50, quantityOrigLong=50, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("CancelOrder [securityId=13, price=8, side=BUY, qty=50, origOrderId=2, cancelId=2, cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.5, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-5.0, usdUnrealized=-5.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=40, qty_scale=0, side=BUY, orderId=3, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=40, quantityOrigLong=40, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");


    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=40, qty_scale=0, side=SELL, orderId=4, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[0], ordType=LIMIT, type=1, priceInt=8, quantityLong=40, quantityOrigLong=40, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    //primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-371, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-3.7100000000000004, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-0.8, usdUnrealized=-0.8, usdRealized=0.0, quotedUsdMark=8.0, settleCoinUsdMark=1.0, settleCoinUnrealized=-0.8, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=BUY, ordType=LIMIT, account=[1, 0, 0], orderId=3, secondaryOrderId=0, execId=1, secondaryExecId=1, feeQty=-1, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=1, isPaidToInsurance=true, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=360, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=3.6, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=SELL, ordType=LIMIT, account=[0], orderId=4, secondaryOrderId=0, execId=1, secondaryExecId=1, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=0, isPaidToInsurance=false, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-451, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-4.510000000000001, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=5, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=360, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=3.6, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.08000000000000002, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=8.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=SELL, orderId=6, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[0], ordType=LIMIT, type=1, priceInt=8, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-451, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-4.510000000000001, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=-50.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=0, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=BUY, ordType=LIMIT, account=[1, 0, 0], orderId=5, secondaryOrderId=0, execId=2, secondaryExecId=2, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=1, isPaidToInsurance=true, execType=CALCULATED, ordStatus=null]");

    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=0, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=360, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=3.6, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-10, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.08000000000000002, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=8.0, settleCoinUsdMark=1.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");

    primary.expect("DRExecutionReport [securityId=13, clOrdId=[a, u, t, o, c, l, o, s, e], symbol=null, side=SELL, ordType=LIMIT, account=[0], orderId=6, secondaryOrderId=0, execId=2, secondaryExecId=2, feeQty=0, timeInForce=IMMEDIATE_OR_CANCEL, qtyInOrderbook=0, feeInstrumentId=0, isPaidToInsurance=false, execType=CALCULATED, ordStatus=null]");
  }

  //@Test //- fail due to balance added for insurance fund
  public void alDueToNegativeBalanceWhenOpenOrderByNonLiquidizedUser() throws Exception {
    publisher.send(order(1, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(10, 0), Side.BUY, USER_ID_TWO, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=101, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=1, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 1], ordType=LIMIT, type=0, priceInt=10, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    publisher.send(globalStateAdminMessage(1));
    //    primary.expect("GlobalStateAdminMessage []"); //TODO an ack not published

    List<Balance> balanceList = createBalanceList(-50, -50, -50);
    publisher.send(balanceAdminMessage(USER_ID_ONE, 1, 1, 1, balanceList));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");


    drainAll();
  }

  //@Test // fail due to balance added for insurance fund
  public void alDueToNegativeBalanceOpenOrder() throws Exception {
    publisher.send(order(1, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(10, 0), Side.BUY, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=1, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    publisher.send(order(2, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(10, 0), Side.BUY, 101, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=101, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=10, qty_scale=0, side=BUY, orderId=2, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 1], ordType=LIMIT, type=0, priceInt=10, quantityLong=10, quantityOrigLong=10, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    publisher.send(globalStateAdminMessage(1));
    //    primary.expect("GlobalStateAdminMessage []"); //TODO an ack not published

    List<Balance> balanceList = createBalanceList(-50, -50, -50);
    publisher.send(balanceAdminMessage(USER_ID_ONE, 1, 1, 1, balanceList));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=-50, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");

    drainAll();
  }

  //@Test (timeout = 250000)
  public void alDueToLeverageRatioExceedSell() throws Exception {

    System.out.println("XX Starting test");
    primary.clearMessageQueues();
    publisher.send(globalStateAdminMessage(1));

    int orderIdOne = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdOne, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(225, 0), Side.SELL, 104, "ClOrdId"));

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.NEW_ORDER);

    //primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    //primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=225, qty_scale=0, side=SELL, orderId="+orderIdOne+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=225, quantityOrigLong=225, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.CANCEL_ORDER);

    //primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    //primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=225, origOrderId="+orderIdOne+", cancelId="+orderIdOne+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    int orderIdFour = currentOrderID.incrementAndGet();
    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.NEW_ORDER);

    //primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    //primary.expect("Order [securityId=13, price=0, price_scale=0, price2=0, price2_scale=0, qty=20, qty_scale=0, side=SELL, orderId=2, orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=0, quantityLong=20, quantityOrigLong=20, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    //TODO Why cancel order
    primary.expectMessage(MessageType.CANCEL_ORDER);
    //primary.expect("CancelOrder [securityId=13, price=0, side=SELL, qty=20, origOrderId=2, cancelId=2, cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=0, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.assertMessages();

    drainAll();
  }

  //@Test
  public void alDueToLeverageRatioExceedBuyStopLimit() throws Exception {
  }

  //@Test
  public void alDueToLeverageRatioExceedMultipleBuy() throws Exception {
    publisher.send(globalStateAdminMessage(1));

    int orderIdOne = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdOne, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(100, 0), Side.BUY, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=100, qty_scale=0, side=BUY, orderId="+orderIdOne+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=100, quantityOrigLong=100, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdTwo = currentOrderID.incrementAndGet();
    publisher.send(order(2, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(80, 0), Side.BUY, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=80, qty_scale=0, side=BUY, orderId="+orderIdTwo+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=80, quantityOrigLong=80, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdThree = currentOrderID.incrementAndGet();
    publisher.send(order(3, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(22, 0), Side.BUY, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=22, qty_scale=0, side=BUY, orderId="+orderIdThree+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=22, quantityOrigLong=22, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=BUY, qty=22, origOrderId="+orderIdThree+", cancelId="+orderIdThree+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=BUY, qty=80, origOrderId="+orderIdTwo+", cancelId="+orderIdTwo+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=BUY, qty=100, origOrderId="+orderIdOne+", cancelId="+orderIdOne+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    int orderIdFour = currentOrderID.incrementAndGet();
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=20, qty_scale=0, side=SELL, orderId="+orderIdFour+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=8, quantityLong=20, quantityOrigLong=20, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    //TODO Why cancel order
    primary.expect("CancelOrder [securityId=13, price=8, side=SELL, qty=20, origOrderId="+orderIdFour+", cancelId="+orderIdFour+", cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");
  }

  //@Test
  public void alDueToLeverageRatioExceedMultipleSell() throws Exception {
    publisher.send(globalStateAdminMessage(1));
    //    primary.expect("GlobalStateAdminMessage []"); //TODO an ack not published
    int orderIdOne = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdOne, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(100, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=100, qty_scale=0, side=SELL, orderId="+orderIdOne+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=100, quantityOrigLong=100, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdTwo = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdTwo, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(80, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=80, qty_scale=0, side=SELL, orderId="+orderIdTwo+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=80, quantityOrigLong=80, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdThree = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdThree, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(45, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=45, qty_scale=0, side=SELL, orderId="+orderIdThree+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=45, quantityOrigLong=45, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=45, origOrderId="+orderIdThree+", cancelId="+orderIdThree+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=80, origOrderId="+orderIdTwo+", cancelId="+orderIdTwo+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=100, origOrderId="+orderIdOne+", cancelId="+orderIdOne+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    int orderIdFour = currentOrderID.incrementAndGet();
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=20, qty_scale=0, side=SELL, orderId="+orderIdFour+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=8, quantityLong=20, quantityOrigLong=20, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    //TODO Why cancel order
    primary.expect("CancelOrder [securityId=13, price=8, side=SELL, qty=20, origOrderId="+orderIdFour+", cancelId="+orderIdFour+", cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");
  }

  @Test (timeout = 250_000)
  public void alDueToNegativeBalanceWhenOpenOrderFromOtherUsers() throws Exception {
    System.out.println("XX Starting test alDueTo");

    primary.clearMessageQueues();
    publisher.send(order(1, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(10, 0), Side.SELL, 105, "ClOrdId"));

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.NEW_ORDER);

    publisher.send(globalStateAdminMessage(1));

    List<Balance> balanceList = createBalanceList(-1, -1, -1);

    publisher.send(balanceAdminMessage(USER_ID_FIVE, 1, 1, 1, balanceList));
    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.BALANCE_ADMIN);

    primary.expectMessage(MessageType.NEW_ORDER);
    primary.expectMessage(MessageType.CANCEL_ORDER);

    primary.expectMessage(MessageType.NEW_ORDER);
    primary.expectMessage(MessageType.CANCEL_ORDER);

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.NEW_ORDER);

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    primary.expectMessage(MessageType.NEW_ORDER);

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    //primary.expectMessage(MessageType.EXECUTION_REPORT);

    primary.expectMessage(MessageType.BALANCE_ADMIN);
    //primary.expectMessage(MessageType.EXECUTION_REPORT);

    primary.assertMessages();

    drainAll();
  }

  //@Test
  public void alDueToLeverageRatioWhenMultipleOpenOrdersFromOtherUsers() throws Exception {
    publisher.send(globalStateAdminMessage(1));
    //    primary.expect("GlobalStateAdminMessage []"); //TODO an ack not published
    int orderIdOne = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdOne, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(100, 0), Side.SELL, 101, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=101, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=100, qty_scale=0, side=SELL, orderId="+orderIdOne+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 1], ordType=LIMIT, type=1, priceInt=10, quantityLong=100, quantityOrigLong=100, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdTwo = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdTwo, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(80, 0), Side.SELL, 101, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=101, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=80, qty_scale=0, side=SELL, orderId="+orderIdTwo+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 1], ordType=LIMIT, type=1, priceInt=10, quantityLong=80, quantityOrigLong=80, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdThree = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdThree, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(45, 0), Side.SELL, 101, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=101, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.4, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=40.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=40, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=4.0, usdUnrealized=4.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=45, qty_scale=0, side=SELL, orderId="+orderIdThree+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 1], ordType=LIMIT, type=1, priceInt=10, quantityLong=45, quantityOrigLong=45, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdFour = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdFour, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(100, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=100, qty_scale=0, side=SELL, orderId="+orderIdFour+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=100, quantityOrigLong=100, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdFive = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdFive, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(80, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=80, qty_scale=0, side=SELL, orderId="+orderIdFive+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=80, quantityOrigLong=80, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    int orderIdSix = currentOrderID.incrementAndGet();
    publisher.send(order(orderIdSix, SECURITY_ID_PAIR, new DecimalFloat(10, 0), new DecimalFloat(45, 0), Side.SELL, 100, "ClOrdId"));
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=10, price_scale=0, price2=0, price2_scale=0, qty=45, qty_scale=0, side=SELL, orderId="+orderIdSix+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[C, l, O, r, d, I, d], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=10, quantityLong=45, quantityOrigLong=45, quantityOrig_scale=0, timeInForce=1, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=45, origOrderId="+orderIdSix+", cancelId="+orderIdSix+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=80, origOrderId="+orderIdFive+", cancelId="+orderIdFive+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    primary.expectMessage(MessageType.EXECUTION_REPORT); //TODO pending cancel Execution parse error
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("CancelOrder [securityId=13, price=10, side=SELL, qty=100, origOrderId="+orderIdFour+", cancelId="+orderIdFour+", cancelPriority=0, clOrdId=[C, l, O, r, d, I, d], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=10, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");

    int orderIdSeven = currentOrderID.incrementAndGet();
    primary.expect("BalanceAdminMessage [senderCompId=EXEC, connectionId=0, triggerTimeMillis=0, userType=0, updateType=PUT, userId=100, firmId=0, txType=0, txId=0, feeTier=0, requestStatus=null, routeToDestination=null, balanceList=[Balance [assetId=1, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=0.2, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=0.010000000000000002, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=12, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=20.0, usdUnrealized=0.0, usdRealized=0.0, quotedUsdMark=1.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0], Balance [assetId=13, balance=20, balance_change=0, eventType=0, orderId=0, execId=0, usdCostBasis=0.0, usdAvgCostBasis=0.0, usdValue=2.0, usdUnrealized=2.0, usdRealized=0.0, quotedUsdMark=10.0, settleCoinUsdMark=0.0, settleCoinUnrealized=0.0, settleCoinRealized=0.0]]]");
    primary.expect("Order [securityId=13, price=8, price_scale=0, price2=0, price2_scale=0, qty=20, qty_scale=0, side=SELL, orderId="+orderIdSeven+", orderPriority=0, secondaryOrderId=0, marginCheckReferencePrice=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompIdCharArr=null, senderCompAsString=null, account=[1, 0, 0], ordType=LIMIT, type=1, priceInt=8, quantityLong=20, quantityOrigLong=20, quantityOrig_scale=0, timeInForce=IMMEDIATE_OR_CANCEL, expireTime=null, stopPx=0, stopPx_scale=0, stopPxInt=0, toClose=false, inputTime=0, decodedTime=0]");

    //TODO Why cancel order
    primary.expect("CancelOrder [securityId=13, price=8, side=SELL, qty=20, origOrderId="+orderIdSeven+", cancelId="+orderIdSeven+", cancelPriority=0, clOrdId=[a, u, t, o, c, l, o, s, e], senderCompId=EXEC, account=[1, 0, 0], ordType=LIMIT, type=0, priceInt=8, quantityLong=0, quantityOrigLong=0, secondaryOrderId=0, inputTime=0, decodedTime=0]");
  }

  //@Test
  public void alDueToLeverageRatioWhenMultipleBuyAndSellOpenOrdersFromOtherUsers() throws Exception {
  }
}

