FIX_HOST=127.0.0.1
#FIX_PORT=9999
FIX_PORT=44999
STREAM_ID=1
USE_AERON=false
ENGINE_INBOUND_CHANNEL=aeron:udp?endpoint=localhost:40001|reliable=true
ENGINE_OUTBOUND_CHANNEL=aeron:udp?endpoint=localhost:40002|reliable=true
MEDIA_DRIVER_DIRECTORY=/aeron-data
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

INITIAL_USER_CACHE_SIZE=10000
QUEUE_CAPACITY=10000
INITIAL_ORDER_BOOK_SIZE=10000

#DB_URL=jdbc:mysql://localhost:3306/trader?
#DB_USER=trader
#DB_PASSWORD=h5!0xhnwnu89sVD38g1
#DB_URL=jdbc:postgresql://34.239.220.159:5432/wildfly
DB_URL=jdbc:postgresql://localhost:5432/wildfly
DB_USER=bijiedev
DB_PASSWORD=Csap2012

USER_LIST=chris/password,raakhee/password,steve/password

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/data/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/data/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/data/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/data/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/Users/rohanw/solfiniorg/downloads
CHRONICLE_ENGINE_SNAP_CACHE_DIRECTORY=/mnt/data/cache

ME_KAFKA_TOPIC=me10000001

POLYGON_WEB3_PROVIDER=https://polygon-amoy.g.alchemy.com/v2/1MH6JeN9slpV-Qh0x31QeMl4pOnRHq94
SIGNER_REQUEST_SECRET=t11CgWqkvf_0dgXL_c7wOf9YQTkLIQMYctiVc2keS6c=
SIGNER_URL=http://10.12.0.2:8080/solfini-signer

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=carbon.credit.test@gmail.com
mail.password=OkABD577J6f39nRo3EAEYQd6Xa_eaFMvGxKBOmD6axI=
mail.from=carbon.credit.test@gmail.com

POSITION_MANAGER_CHAIN=POLYGON_AMOY
POSITION_MANAGER_RPC_READ_URL=https://polygon-amoy.g.alchemy.com/v2/1MH6JeN9slpV-Qh0x31QeMl4pOnRHq94
POSITION_MANAGER_RPC_URL=https://polygon-amoy.g.alchemy.com/v2/1MH6JeN9slpV-Qh0x31QeMl4pOnRHq94
POSITION_MANAGER_CONTRACT_ADDRESS=0x268763989D15362a96EA3eDc6A0181fDd1e136fD
POSITION_MANAGER_CALLER_ADDRESS=0x607b6Cd7a24ae36851bDE5d06b6d1002F99bdc53

FUND_MANAGER_CHAIN=POLYGON_AMOY
FUND_MANAGER_RPC_READ_URL==https://polygon-amoy.g.alchemy.com/v2/1MH6JeN9slpV-Qh0x31QeMl4pOnRHq94
FUND_MANAGER_RPC_URL=https://polygon-amoy.g.alchemy.com/v2/1MH6JeN9slpV-Qh0x31QeMl4pOnRHq94
FUND_MANAGER_CONTRACT_ADDRESS=0x24278a7D5befb91E44D5609c7663Cbe2947cEB60
FUND_MANAGER_CALLER_ADDRESS=0x607b6Cd7a24ae36851bDE5d06b6d1002F99bdc53

IGNORE_SYMBOL_LIST=963,964,965,966,978,979,980,981,982,983,984,985,987,988,989,990,991,992,993,994


