FIX_HOST=127.0.0.1
#FIX_PORT=9999
FIX_PORT=44999
STREAM_ID=1
USE_AERON=false
ENGINE_INBOUND_CHANNEL=aeron:udp?endpoint=localhost:40001|reliable=true
ENGINE_OUTBOUND_CHANNEL=aeron:udp?endpoint=localhost:40002|reliable=true
MEDIA_DRIVER_DIRECTORY=/aeron-data
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608

#DB_URL=jdbc:mysql://localhost:3306/trader?
#DB_USER=trader
#DB_PASSWORD=h5!0xhnwnu89sVD38g1
#DB_URL=jdbc:postgresql://34.239.220.159:5432/wildfly
DB_URL=jdbc:postgresql://localhost:5432/wildfly
DB_USER=bijiedev
DB_PASSWORD=Csap2012

USER_LIST=chris/password,raakhee/password,steve/password

  
CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/chronicle/engine-balance

MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/reports/balance-history

ME_KAFKA_TOPIC=me10000001