INSTANCE_ID=me01

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608

DB_URL=jdbc:postgresql://localhost:5432/wildfly
DB_USER=bijiedev
DB_PASSWORD=Csap2012

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/efs/snap

MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/reports/balance-history

ACK_REJECT_MESSAGES=true
PUBLISH_MARKET_DATA=true
LISTEN_TO_IPC_MARKET_DATA=true
INITIAL_USER_CACHE_SIZE=1048576
STATE_VALIDATOR_ENABLED=TRUE

ME_KAFKA_TOPIC_PRIMARY=me10000016b
ME_KAFKA_TOPIC_SECONDARY=me10000016b_dr
API_KAFKA_TOPIC_IN=api16b
MD_KAFKA_TOPIC_IN=md1

LOAD_FROM_SNAP=1565870600569701707
LOAD_FROM_SNAP_AND_REPLAY=OUTPUT

CONTROLLER_TYPE=unified
CONTROLLER_MODE=primary
CONTROLLER_ZOOKEEPER_LOCATION=172.31.71.223:2181
CONTROLLER_ZOOKEEPER_PRIORITY=1

KAFKA.CONSUMER.bootstrap.servers=172.31.71.223:4455
KAFKA.CONSUMER.group.id=me01
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

KAFKA.PRODUCER.bootstrap.servers=172.31.71.223:4455
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.auto.commit.interval.ms=10
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true
KAFKA.PRODUCER.compression.type=snappy
