INSTANCE_ID=me01

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=65536
INITIAL_USER_CACHE_SIZE=65536
INITIAL_ORDER_BOOK_SIZE=65536
BALANCE_ADMIN_POOL_QUEUE_CAPACITY=65536
BALANCE_ADMIN_POOL_START_CAPACITY=65536
BUSINESS_REJECT_POOL_QUEUE_CAPACITY=65536
BUSINESS_REJECT_POOL_START_CAPACITY=65536
BYTE_BUFFER_POOL_QUEUE_CAPACITY=65536
BYTE_BUFFER_POOL_START_CAPACITY=65536
CANCEL_ORDER_POOL_QUEUE_CAPACITY=65536
CANCEL_ORDER_POOL_START_CAPACITY=65536
CANCEL_REJECT_POOL_QUEUE_CAPACITY=65536
CANCEL_REJECT_POOL_START_CAPACITY=65536
EXECUTION_REPORT_POOL_QUEUE_CAPACITY=65536
EXECUTION_REPORT_POOL_START_CAPACITY=65536
KAFKA_PRODUCER_POOL_QUEUE_CAPACITY=65536
KAFKA_PRODUCER_POOL_START_CAPACITY=65536
LIQUIDATION_ORDER_POOL_QUEUE_CAPACITY=65536
LIQUIDATION_ORDER_POOL_START_CAPACITY=65536
LOG_POOL_QUEUE_CAPACITY=65536
LOG_POOL_START_CAPACITY=65536
ORDER_POOL_QUEUE_CAPACITY=65536
ORDER_POOL_START_CAPACITY=65536
POSITION_POOL_QUEUE_CAPACITY=65536
POSITION_POOL_START_CAPACITY=65536
POSITION_REPORT_PARSER_START_CAPACITY=65536
POSITION_REPORT_POOL_QUEUE_CAPACITY=65536
POSITION_REPORT_POOL_START_CAPACITY=65536
RecieverData_POOL_QUEUE_CAPACITY=65536
RecieverData_POOL_START_CAPACITY=65536
STRING_BUILDER_POOL_QUEUE_CAPACITY=65536
STRING_BUILDER_POOL_START_CAPACITY=65536
USER_OPEN_ORDERS_POOL_QUEUE_CAPACITY=65536
USER_OPEN_ORDERS_POOL_START_CAPACITY=65536

DB_URL=jdbc:postgresql://localhost:5432/wildfly
DB_USER=bijiedev
DB_PASSWORD=Csap2012

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/snap

MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/reports/balance-history

ACK_REJECT_MESSAGES=true
PUBLISH_MARKET_DATA=false
INITIAL_USER_CACHE_SIZE=1048576

ME_KAFKA_TOPIC_PRIMARY=primary_out
ME_KAFKA_TOPIC_SECONDARY=secondary_out
API_KAFKA_TOPIC_IN=api_in

LOAD_FROM_SNAP=10000001
LOAD_FROM_SNAP_AND_REPLAY=OUTPUT

CONTROLLER_TYPE=kafka
CONTROLLER_MODE=primary
CONTROLLER_ZOOKEEPER_LOCATION=zookeeper:2181
CONTROLLER_ZOOKEEPER_PRIORITY=0
CONTROLLER_ZOOKEEPER_SESSION_TIMEOUT=20
CONTROLLER_ZOOKEEPER_CONNECTION_TIMEOUT=60

KAFKA.CONSUMER.bootstrap.servers=kafka:4455
KAFKA.CONSUMER.group.id=matching-engine-01
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000

KAFKA.PRODUCER.bootstrap.servers=kafka:4455
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true
KAFKA.PRODUCER.compression.type=snappy

DEBUG_LOG_RISK=true
CHRONICLE_ENGINE_SNAP_CACHE_DIRECTORY=/tmp/snap_cache
