INSTANCE_ID=me01

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608

#DB_URL=jdbc:postgresql://localhost:5432/wildfly
#DB_USER=bijiedev
#DB_PASSWORD=Csap2012
DB_URL=jdbc:postgresql://solfini.com:5432/trader
DB_USER=trader2
DB_PASSWORD=asdhkjh1zx31


CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/data/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/data/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/data/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/data/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/mnt/data/snap

MM_EXECUTION_REPORT_DIRECTORY=/mnt/data/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/mnt/data/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/data/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/data/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/data/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/data/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/data/reports/balance-history

QUEUE_CAPACITY=100000
INITIAL_USER_CACHE_SIZE=1000
INITIAL_ORDER_BOOK_SIZE=100000
BALANCE_ADMIN_POOL_QUEUE_CAPACITY=100000
BALANCE_ADMIN_POOL_START_CAPACITY=100000
BUSINESS_REJECT_POOL_QUEUE_CAPACITY=100000
BUSINESS_REJECT_POOL_START_CAPACITY=100000
BYTE_BUFFER_POOL_QUEUE_CAPACITY=1000000
BYTE_BUFFER_POOL_START_CAPACITY=1000000
CANCEL_ORDER_POOL_QUEUE_CAPACITY=100000
CANCEL_ORDER_POOL_START_CAPACITY=100000
CANCEL_REJECT_POOL_QUEUE_CAPACITY=100000
CANCEL_REJECT_POOL_START_CAPACITY=100000
EXECUTION_REPORT_POOL_QUEUE_CAPACITY=1000000
EXECUTION_REPORT_POOL_START_CAPACITY=1000000
KAFKA_PRODUCER_POOL_QUEUE_CAPACITY=1000000
KAFKA_PRODUCER_POOL_START_CAPACITY=1000000
LIQUIDATION_ORDER_POOL_QUEUE_CAPACITY=100000
LIQUIDATION_ORDER_POOL_START_CAPACITY=100000
LOG_POOL_QUEUE_CAPACITY=100000
LOG_POOL_START_CAPACITY=100000
ORDER_POOL_QUEUE_CAPACITY=1000000
ORDER_POOL_START_CAPACITY=1000000
POSITION_POOL_QUEUE_CAPACITY=1000000
POSITION_POOL_START_CAPACITY=1000000
POSITION_REPORT_POOL_QUEUE_CAPACITY=1000000
POSITION_REPORT_POOL_START_CAPACITY=1000000
RecieverData_POOL_QUEUE_CAPACITY=1000000
RecieverData_POOL_START_CAPACITY=1000000
STRING_BUILDER_POOL_QUEUE_CAPACITY=100000
STRING_BUILDER_POOL_START_CAPACITY=100000
USER_OPEN_ORDERS_POOL_QUEUE_CAPACITY=1000000
USER_OPEN_ORDERS_POOL_START_CAPACITY=1000000

ACK_REJECT_MESSAGES=true
PUBLISH_MARKET_DATA=true
LISTEN_TO_IPC_MARKET_DATA=true
INITIAL_USER_CACHE_SIZE=1048576

ME_KAFKA_TOPIC_PRIMARY=me0001
ME_KAFKA_TOPIC_SECONDARY=me0001dr
API_KAFKA_TOPIC_IN=api0001
MD_KAFKA_TOPIC_IN=md0001

LOAD_FROM_SNAP=1570690870698374943
LOAD_FROM_SNAP_AND_REPLAY=OUTPUT
STATE_VALIDATOR_ENABLED=FALSE
PERSIST_MODE_ENABLED=FALSE


CONTROLLER_TYPE=unified
CONTROLLER_MODE=primary
CONTROLLER_ZOOKEEPER_LOCATION=207.180.237.240:2181
CONTROLLER_ZOOKEEPER_PRIORITY=1

KAFKA.CONSUMER.bootstrap.servers=207.180.237.240:4455
KAFKA.CONSUMER.group.id=me01
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

KAFKA.PRODUCER.bootstrap.servers=207.180.237.240:4455
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.auto.commit.interval.ms=10
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true
KAFKA.PRODUCER.compression.type=snappy
