INSTANCE_ID=me01

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
USE_AERON=false
ENGINE_INBOUND_CHANNEL=aeron:udp?endpoint=localhost:40001|reliable=true
ENGINE_OUTBOUND_CHANNEL=aeron:udp?endpoint=localhost:40002|reliable=true
MEDIA_DRIVER_DIRECTORY=/aeron-data
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608

#DB_URL=jdbc:postgresql://tk-dev-future-me.ctdjwepesacu.ap-northeast-1.rds.amazonaws.com:5432/wildfly
#DB_USER=future_dev
#DB_PASSWORD=future_dev

USER_LIST=chris/password,raakhee/password,steve/password

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/server/futures-me-devops/chronicle/engine-output
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/server/futures-me-devops/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/server/futures-me-devops/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/server/futures-me-devops/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/server/futures-me-devops/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/server/futures-me-devops/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/server/futures-me-devops/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/efs/snap

MM_EXECUTION_REPORT_DIRECTORY=/server/futures-me-devops/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/server/futures-me-devops/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/server/futures-me-devops/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/server/futures-me-devops/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/server/futures-me-devops/mm/user-order-index
MM_BALANCE_DIRECTORY=/server/futures-me-devops/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/server/futures-me-devops/reports/balance-history

#ACK_REJECT_MESSAGES=true
#PUBLISH_MARKET_DATA=true
INITIAL_USER_CACHE_SIZE=1048576

ME_KAFKA_TOPIC_PRIMARY=me10000009
ME_KAFKA_TOPIC_SECONDARY=me10000009_dr
API_KAFKA_TOPIC_IN=api9
MD_KAFKA_TOPIC_IN=md1

#LOAD_FROM_SNAP=1563343783986040046
LOAD_FROM_SNAP_AND_REPLAY=OUTPUT

CONTROLLER_TYPE=kafka
CONTROLLER_MODE=primary
CONTROLLER_ZOOKEEPER_LOCATION=10.140.41.169:2181,10.140.43.246:2181,10.140.42.211:2181

KAFKA.CONSUMER.bootstrap.servers=10.140.41.169:9092,10.140.43.246:9092,10.140.42.211:9092
KAFKA.CONSUMER.group.id=me01
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

KAFKA.PRODUCER.bootstrap.servers=10.140.41.169:9092,10.140.43.246:9092,10.140.42.211:9092
KAFKA.PRODUCER.compression.type=snappy
KAFKA.PRODUCER.acks=1
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.auto.commit.interval.ms=10
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true

LOG_LEVEL=debug
ACK_REJECT_MESSAGES=false
PUBLISH_MARKET_DATA=false

LISTEN_TO_KAFKA_MARKET_DATA=true
DEFAULT_SETTLE_INSTRUMENT_PRICE_SCALE_MULT=100000000
DEFAULT_SETTLE_INSTRUMENT_QUANTITY_SCALE_MULT=100000000
DEFAULT_SETTLE_INSTRUMENT_QUANTITY_SCALE=8
ENABLE_BALANCE_WITHDRAW_LIMITS=false

AUTOMATIC_LOG_DISABLE_ON_LATENCY=false
MAX_LATENCY_FOR_LOG_DISABLE_MS=1000
MIN_LATENCY_FOR_LOG_ENABLE_MS=500

BTC_USDT_FUTURE_SYMBOL=BTCUSDT
ETH_USDT_FUTURE_SYMBOL=ETHUSDT
ETH_USDT_SPOT_SYMBOL=ETHUSDT
BTC_USDT_SPOT_SYMBOL=BTCUSDT

STATE_VALIDATOR_ENABLED=TRUE


ORDER_POOL_QUEUE_CAPACITY=8388608
ORDER_POOL_START_CAPACITY=4194304
LIQUIDATION_ORDER_POOL_QUEUE_CAPACITY=1048576
LIQUIDATION_ORDER_POOL_START_CAPACITY=524288
POSITION_POOL_QUEUE_CAPACITY=16777216
POSITION_POOL_START_CAPACITY=8388608
USER_OPEN_ORDERS_POOL_QUEUE_CAPACITY=16777216
USER_OPEN_ORDERS_POOL_START_CAPACITY=8388608

