INSTANCE_ID=me01

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

DB_URL=jdbc:postgresql://10.20.0.15:5432/db
DB_USER=db
DB_PASSWORD=

EXTERNAL_DB_URL=jdbc:mysql://10.20.0.12:3306/mp_prod
EXTERNAL_DB_USER=sentiment
EXTERNAL_DB_PASSWORD=

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/data/bitoderly_snap/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/data/bitoderly_snap/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/data/bitoderly_snap/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/data/bitoderly_snap/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/data/bitoderly_snap/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/data/bitoderly_snap/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/data/bitoderly_snap/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/data/bitoderly_snap/snap
CHRONICLE_ENGINE_SNAP_CACHE_DIRECTORY=/data/bitoderly_snap/cache

MM_ORDER_BOOK_INDEX_DIRECTORY=/data/bitoderly_snap/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/data/bitoderly_snap/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/data/bitoderly_snap/mm/user-order-index
MM_BALANCE_DIRECTORY=/data/bitoderly_snap/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/data/bitoderly_snap/reports/balance-history

QUEUE_CAPACITY=131072
INITIAL_USER_CACHE_SIZE=1000
INITIAL_ORDER_BOOK_SIZE=7000000
BALANCE_ADMIN_POOL_QUEUE_CAPACITY=1000000
BALANCE_ADMIN_POOL_START_CAPACITY=1000000
BUSINESS_REJECT_POOL_QUEUE_CAPACITY=1000000
BUSINESS_REJECT_POOL_START_CAPACITY=1000000
BYTE_BUFFER_POOL_QUEUE_CAPACITY=1000000
BYTE_BUFFER_POOL_START_CAPACITY=1000000
CANCEL_ORDER_POOL_QUEUE_CAPACITY=10000
CANCEL_ORDER_POOL_START_CAPACITY=10000
CANCEL_REJECT_POOL_QUEUE_CAPACITY=10000
CANCEL_REJECT_POOL_START_CAPACITY=10000
EXECUTION_REPORT_POOL_QUEUE_CAPACITY=1000000
EXECUTION_REPORT_POOL_START_CAPACITY=1000000
KAFKA_PRODUCER_POOL_QUEUE_CAPACITY=1000000
KAFKA_PRODUCER_POOL_START_CAPACITY=1000000
LIQUIDATION_ORDER_POOL_QUEUE_CAPACITY=1000
LIQUIDATION_ORDER_POOL_START_CAPACITY=1000
LOG_POOL_QUEUE_CAPACITY=1000000
LOG_POOL_START_CAPACITY=1000000
ORDER_POOL_QUEUE_CAPACITY=1000000
ORDER_POOL_START_CAPACITY=1000000
POSITION_POOL_QUEUE_CAPACITY=1000000
POSITION_POOL_START_CAPACITY=1000000
POSITION_REPORT_POOL_QUEUE_CAPACITY=1000000
POSITION_REPORT_POOL_START_CAPACITY=1000000
RecieverData_POOL_QUEUE_CAPACITY=100000
RecieverData_POOL_START_CAPACITY=100000
STRING_BUILDER_POOL_QUEUE_CAPACITY=100000
STRING_BUILDER_POOL_START_CAPACITY=100000
USER_OPEN_ORDERS_POOL_QUEUE_CAPACITY=100000
USER_OPEN_ORDERS_POOL_START_CAPACITY=100000

ACK_REJECT_MESSAGES=false
PUBLISH_MARKET_DATA=false
LISTEN_TO_IPC_MARKET_DATA=false
LISTEN_TO_KAFKA_MARKET_DATA=false

ME_KAFKA_TOPIC_PRIMARY=me01
ME_KAFKA_TOPIC_SECONDARY=me01dr
API_KAFKA_TOPIC_IN=api01
MD_KAFKA_TOPIC_IN=md01

LOAD_FROM_SNAP=1784755761534673300
LOAD_FROM_SNAP_AND_REPLAY=NONE
STATE_VALIDATOR_ENABLED=FALSE
PERSIST_MODE_ENABLED=FALSE
MARKET_MAKER_USERID=0

CONTROLLER_TYPE=unified
CONTROLLER_MODE=primary
CONTROLLER_ZOOKEEPER_LOCATION=127.0.0.1:2181
CONTROLLER_ZOOKEEPER_PRIORITY=1

#KAFKA.CONSUMER.bootstrap.servers=10.20.0.11:9092
KAFKA.CONSUMER.bootstrap.servers=10.20.0.14:9092
KAFKA.CONSUMER.group.id=me01
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=1000
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

#KAFKA.PRODUCER.bootstrap.servers=10.20.0.11:9092
KAFKA.PRODUCER.bootstrap.servers=10.20.0.14:9092
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.compression.type=none

AUCTIONS_ENABLED=false
PRICING_THREAD_ENABLED=false
PERPETUALS_ENABLED=false
CONTRACT_EXPIRY_ENABLED=false
COLLATERAL_SWAP_ENABLED=false
CROSS_COLLATERAL_ENABLED=false
ENABLE_CIRCUIT_BREAKER=false

GENERATE_FUNDING_RATE_EVENT=false
ASSET_GROUPS_COMPACTION_TOPIC=assetgroups

ENVIRONMENT=PRODUCTION
COPY_TRADE_ENABLED=FALSE
ROUTER_THREAD_POOL_CORE_SIZE=1
COPY_TRADE_ONLY=FALSE
COPY_TRADE_PROXY_IPS=46.250.254.218,46.250.254.217,185.229.119.238
PUBLISH_HEALTH_REPORT_MAIL=false

BLOCKCHAIN_POSITION_MANAGER_ENABLED=false
POLYGON_WEB3_PROVIDER=https://polygon-mainnet.g.alchemy.com/v2/v0rz-6lAjjQq9g-y2_acDX5EaMrLUhVh
SIGNER_REQUEST_SECRET=AkyLeXub430A3YS4BytkvzCB_ibSPN-S9pQOz0c6DH4=
SIGNER_URL=http://10.20.0.11:9081/solfini-signer
POSITION_MANAGER_CHAIN=POLYGON
POSITION_MANAGER_CONTRACT_ADDRESS=0xf857aC7bed76B43c5457f56483803C4CebbD7eff
GAS_LIMIT_FOR_POSITION_UPDATE=1000000

FUND_MANAGER_CHAIN=ETHEREUM
FUND_MANAGER_CONTRACT_ADDRESS=0x8815e8F0eb65E1072518e8F842C3aD5199DFCEF1

STAKE_SYMBOL_IDS=4,5,913,914,915,916,917,918
VTOKEN_SYMBOL_IDS=6,7
ENABLE_DETAIL_LOGS_FOR_USER_ID=0
LIQUIDITY_INSTRUMENT_PAIR_ID=10
FUNDING_RATE_INTEREST_RATE=10.95

LIQUIDITY_DEX_ENABLED=false

BINANCE_EXCHANGE_BASE_URL=https://api.binance.com
BINANCE_FUTURES_EXCHANGE_BASE_URL=https://fapi.binance.com
BYBIT_EXCHANGE_BASE_URL=https://api.bybit.com
BYBIT_EXCHANGE_RECV_WINDOW=10000

SAFETY_FACTOR_BPS_FOR_LIQUIDITY=0.002
COST_BASIS_PUBLISH_SCALE=8

TEST_USERS=
OUTBOUND_IP=51.79.137.53
RECONCILIATION_ALERT_EMAILS=alerts.rohanw@gmail.com,chris@quote.trade,iroshnk@gmail.com,alerts.mihindu@gmail.com

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=carbon.credit.test@gmail.com
mail.password=OkABD577J6f39nRo3EAEYQd6Xa_eaFMvGxKBOmD6axI=
mail.from=carbon.credit.test@gmail.com
