INSTANCE_ID=me02

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1
INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

DB_URL=jdbc:postgresql://<IP>:5432/<DB>
DB_USER=<DB_USER>
DB_PASSWORD=<PASSWORD>

# Market profit data
EXTERNAL_DB_URL=jdbc:mysql://<IP>:3306/<DB>
EXTERNAL_DB_USER=<DB_USER>
EXTERNAL_DB_PASSWORD=<PASSWORD>

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/data/chronicle/engine-output
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/data/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/data/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/data/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/data/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/mnt/data/snap
CHRONICLE_ENGINE_SNAP_CACHE_DIRECTORY=/mnt/data/cache

MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/data/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/data/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/data/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/data/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/data/reports/balance-history

QUEUE_CAPACITY=131072
INITIAL_USER_CACHE_SIZE=1000
INITIAL_ORDER_BOOK_SIZE=7000000
BALANCE_ADMIN_POOL_QUEUE_CAPACITY=10000
BALANCE_ADMIN_POOL_START_CAPACITY=10000
BUSINESS_REJECT_POOL_QUEUE_CAPACITY=10000
BUSINESS_REJECT_POOL_START_CAPACITY=10000
BYTE_BUFFER_POOL_QUEUE_CAPACITY=100000
BYTE_BUFFER_POOL_START_CAPACITY=100000
CANCEL_ORDER_POOL_QUEUE_CAPACITY=10000
CANCEL_ORDER_POOL_START_CAPACITY=10000
CANCEL_REJECT_POOL_QUEUE_CAPACITY=10000
CANCEL_REJECT_POOL_START_CAPACITY=10000
EXECUTION_REPORT_POOL_QUEUE_CAPACITY=200000
EXECUTION_REPORT_POOL_START_CAPACITY=100000
KAFKA_PRODUCER_POOL_QUEUE_CAPACITY=100000
KAFKA_PRODUCER_POOL_START_CAPACITY=100000
LIQUIDATION_ORDER_POOL_QUEUE_CAPACITY=1000
LIQUIDATION_ORDER_POOL_START_CAPACITY=1000
LOG_POOL_QUEUE_CAPACITY=500000
LOG_POOL_START_CAPACITY=500000
ORDER_POOL_QUEUE_CAPACITY=100000
ORDER_POOL_START_CAPACITY=100000
POSITION_POOL_QUEUE_CAPACITY=100000
POSITION_POOL_START_CAPACITY=200000
POSITION_REPORT_POOL_QUEUE_CAPACITY=200000
POSITION_REPORT_POOL_START_CAPACITY=100000
RecieverData_POOL_QUEUE_CAPACITY=100000
RecieverData_POOL_START_CAPACITY=100000
STRING_BUILDER_POOL_QUEUE_CAPACITY=10000
STRING_BUILDER_POOL_START_CAPACITY=10000
USER_OPEN_ORDERS_POOL_QUEUE_CAPACITY=100000
USER_OPEN_ORDERS_POOL_START_CAPACITY=100000

ACK_REJECT_MESSAGES=true
PUBLISH_MARKET_DATA=true
LISTEN_TO_IPC_MARKET_DATA=false
LISTEN_TO_KAFKA_MARKET_DATA=true

ME_KAFKA_TOPIC_PRIMARY=me01
ME_KAFKA_TOPIC_SECONDARY=me01dr
API_KAFKA_TOPIC_IN=api01
MD_KAFKA_TOPIC_IN=md01

LOAD_FROM_SNAP=1786368866093347100
LOAD_FROM_SNAP_AND_REPLAY=SELECTED_INPUT
STATE_VALIDATOR_ENABLED=TRUE
PERSIST_MODE_ENABLED=TRUE
MARKET_MAKER_USERID=0

CONTROLLER_TYPE=zookeeper
CONTROLLER_MODE=secondary
CONTROLLER_ZOOKEEPER_LOCATION=<IP>:2181
CONTROLLER_ZOOKEEPER_PRIORITY=1

KAFKA.CONSUMER.bootstrap.servers=<IP>:9092
KAFKA.CONSUMER.group.id=me02
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

KAFKA.PRODUCER.bootstrap.servers=<IP>:9092
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.auto.commit.interval.ms=10
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true
KAFKA.PRODUCER.compression.type=snappy

AUCTIONS_ENABLED=true
PRICING_THREAD_ENABLED=true
PERPETUALS_ENABLED=true
CONTRACT_EXPIRY_ENABLED=true
COLLATERAL_SWAP_ENABLED=true
CROSS_COLLATERAL_ENABLED=true
ENABLE_CIRCUIT_BREAKER=false

GENERATE_FUNDING_RATE_EVENT=true
ASSET_GROUPS_COMPACTION_TOPIC=assetgroups

ENVIRONMENT=PRODUCTION
COPY_TRADE_ENABLED=FALSE
ROUTER_THREAD_POOL_CORE_SIZE=1
COPY_TRADE_ONLY=FALSE
COPY_TRADE_PROXY_IPS=<List of proxy ips>
PUBLISH_HEALTH_REPORT_MAIL=false

BLOCKCHAIN_POSITION_MANAGER_ENABLED=true
POLYGON_WEB3_PROVIDER=<TODO>
SIGNER_REQUEST_SECRET=<TODO>
SIGNER_URL=http://<IP>:<PORT>/solfini-signer
POSITION_MANAGER_CHAIN=POLYGON
POSITION_MANAGER_CONTRACT_ADDRESS=<TODO>
GAS_LIMIT_FOR_POSITION_UPDATE=1000000

FUND_MANAGER_CHAIN=ETHEREUM
FUND_MANAGER_CONTRACT_ADDRESS=<TODO>

STAKE_SYMBOL_IDS=4,5,913,914,915,916,917,918
VTOKEN_SYMBOL_IDS=6,7
ENABLE_DETAIL_LOGS_FOR_USER_ID=0
LIQUIDITY_INSTRUMENT_PAIR_ID=10
FUNDING_RATE_INTEREST_RATE=10.95

LIQUIDITY_DEX_ENABLED=true

BINANCE_EXCHANGE_BASE_URL=https://api.binance.com
BINANCE_FUTURES_EXCHANGE_BASE_URL=https://fapi.binance.com
BYBIT_EXCHANGE_BASE_URL=https://api.bybit.com
BYBIT_EXCHANGE_RECV_WINDOW=10000

SAFETY_FACTOR_BPS_FOR_LIQUIDITY=0.002
COST_BASIS_PUBLISH_SCALE=8

TEST_USERS=
OUTBOUND_IP=<TODO>
RECONCILIATION_ALERT_EMAILS=alerts.rohanw@gmail.com,chris@quote.trade,iroshnk@gmail.com,alerts.mihindu@gmail.com

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=<TODO>
mail.password=<TODO>
mail.from=<TODO>