package com.solfini.common;

/**
 *
 * @author Chris Mack
 *
 */
public interface Constants {
  // assetTypes
  public static final int ASSET = 0;
  public static final int PAIR = 1;
  public static final int NULL_VAL = 255;

  public static final String USD = "USD";
  public static final String USDC = "USDC";
  public static final String USDT = "USDT";
  public static final String BTC = "BTC";
  public static final String ETH = "ETH";
  public static final String BTC_USD = "BTC/USD";
  public static final String BTC_USDC = "BTC/USDC";

  public static final String ORDER_STATUS_FILLED = "FILLED";

  public static final String SYMBOL_NOT_FOUND = "symbol not found";
  public static final String NO_PRICE = "no price in newOrderSingleDecoder";
  public static final String MARKET_IS_CLOSED = "Market is closed";
  public static final String USER_NOT_FOUND = "User not found";
  public static final String UNABLE_TO_PARSE_ORDER = "Unable to parse order";
  public static final String UNABLE_TO_LOAD_USER = "Unable to load user";
  public static final String FAILED_PRE_CREDIT_CHECK = "Failed pre-credit check";
  public static final String NO_LIQUIDITY_AVAILABLE = "No liquidity available";
  public static final String PRICE_IS_MISSING = "Price is missing";
  public static final String ORDER_WOULD_IMMEDIATELY_TRIGGER = "Order would immediately trigger";
  public static final String PRICE_IS_OUT_OF_BOUNDS = "Price is out of bounds";
  public static final String STOP_PRICE_IS_MISSING = "Stop price is missing";
  public static final String QUANTITY_IS_MISSING = "Quantity is missing";
  public static final String SECURITY_ID_IS_MISSING = "missing SecurityID";
  public static final String MARKET_IS_PAUSED_OR_CLOSED = "Market is paused or closed";
  public static final String MARKET_CIRCUIT_BREAKER = "Market is on circuit breaker";
  public static final String INSTRUMENT_NOT_FOUND = "Instrument not found";
  public static final String BASE_OR_QUOTED_INSTRUMENT_NOT_FOUND = "Base or Quoted Instrument not found";
  public static final String UNABLE_TO_PARSE = "Unable to parse message";
  public static final String INVALID_ORDER_SECURITY = "Order security is invalid";
  public static final String INVALID_ALGO_ORDER_INTERVAL = "Algo Order interval time is too low";
  public static final String ONLY_LIMIT_ORDERS_ALLOWED = "Only limit orders are allowed";
  public static final String INVALID_ORDER_SELECT = "Order select is invalid";
  public static final String ASSET_GROUP_NOT_FOUND = "Asset Group not found";
  public static final String ASSET_GROUP_NOT_AVAILABLE = "Asset Group not available";
  public static final String ASSET_GROUP_NOT_ENOUGH = "Asset Group not enough";


  public static final String TRUE = "true";
  public static final String FALSE = "false";
  public static final String NO_OP_IDLE_STATEGY = "NoOpIdleStrategy";
  public static final String ERROR_LOG = "Error";
  public static final String WARN_LOG = "Warn";
  public static final String MODE = "mode";
  public static final String DEBUG_LOG = "debug";
  public static final String COLD_START = "cold-start";
  public static final String WARM_START = "warm-start";
  public static final String SNAPSHOT_ID = "snapshot-id";
  public static final String PRIMARY = "primary";
  public static final String SECONDARY = "secondary";
  public static final String COPY_TRADE_ONLY = "copy_trade_only";

  public static final int BUY_LIMIT = 0;
  public static final int SELL_LIMIT = 1;
  public static final int BUY_MARKET = 2;
  public static final int SELL_MARKET = 3;
  public static final int DEPOSIT = 4;
  public static final int CANCEL_BUY = 5;
  public static final int CANCEL_SELL = 6;
  public static final int CHANGE_QUANTITY = 7;
  public static final int STOP_BUY_LIMIT = 8;
  public static final int STOP_SELL_LIMIT = 9;
  public static final int STOP_BUY_MARKET = 10;
  public static final int STOP_SELL_MARKET = 11;
  public static final int TRAILING_STOP_BUY_LIMIT = 12;
  public static final int TRAILING_STOP_SELL_LIMIT = 13;
  public static final int BUY_SELECT = 14;
  public static final int SELL_SELECT = 15;

  // target Strategy, defaults to 0 (no strategy)
  public static final int ADL_MAKER_ONLY = 99;
  public static final int REDUCE_ONLY = 101;
  public static final int PROFIT_LIMIT = 120; // reverse trigger of stop limit
  public static final int PROFIT_LIMIT_REDUCE_ONLY = 121; // reverse trigger of stop limit with REDUCE_ONLY
  public static final int PROFIT_MARKET = 130; // reverse trigger of stop limit, with market
  public static final int PROFIT_MARKET_REDUCE_ONLY = 131; // reverse trigger of stop limit with REDUCE_ONLY

  public static final int STOP_MARKET = 150; // stop market, with market
  public static final int STOP_MARKET_REDUCE_ONLY = 151; // stop market with REDUCE_ONLY

  public static final int TRAILING_STOP_LIMIT = 160; // trailing stop limit
  public static final int TRAILING_STOP_LIMIT_REDUCE_ONLY = 161; // trailing stop limit with REDUCE_ONLY
  public static final int TRAILING_STOP_MARKET = 170; // trailing stop market, with market
  public static final int TRAILING_STOP_MARKET_REDUCE_ONLY = 171; // trailing stop market with REDUCE_ONLY

  public static final int TWAP = 180; // TWAP
  public static final int TWAP_REDUCE_ONLY = 181; // TWAP with REDUCE_ONLY
  public static final int FILTERED = 190; // for filtering orderbook


  // order book types
  public static final int TREE_ORDER_BOOK = 1;
  public static final int ARRAY_ORDER_BOOK = 2;
  public static final int LINKED_LIST_ORDER_BOOK = 3;
  public static final int TREE_ORDER_BOOK2 = 4;
  public static final int SELECT_ARRAY_ORDER_BOOK = 5;
  public static final int COPY_TRADE_ORDER_BOOK = 6;
  public static final int FILTER_ARRAY_ORDER_BOOK = 7;

  public static final int DEFAULT_TEST_ORDER_BOOK = ARRAY_ORDER_BOOK;

  public static final int NO_PREORDER_CHECK = 10;
  public static final int CASH_PREORDER_CHECK = 11;
  public static final int MARGIN_PREORDER_CHECK = 12;

  public static final int BALANCE_DEPOSIT = 1;
  public static final int BALANCE_WITHDRAW = 2;
  public static final int BALANCE_FEE = 3;
  public static final int BALANCE_CREDIT = 4;
  public static final int BALANCE_TRADE_SETTLE_BASE = 5;
  public static final int BALANCE_TRADE_SETTLE_QUOTED = 6;
  public static final int BALANCE_TRADE_SETTLE_FEE = 7;

  public static final int SETTLE_TYPE_PHYSICAL = 0;
  public static final int SETTLE_TYPE_CONTRACT = 1;

  public static final int TX_DEPOSIT = 4011;
  public static final int TX_WITHDRAW = 4012;
  public static final int TX_ADMIN_DEPOSIT = 4013;
  public static final int TX_ADMIN_WITHDRAW = 4014;
  public static final int TX_FEE = 4015;
  public static final int TX_ADJUSTMENT = 4016;
  public static final int TX_INVEST_FUND = 4017;
  public static final int TX_DIVEST_FUND = 4018;
  public static final int TX_TRADE_FILL = 4019;
  public static final int TX_FUNDING_RATE = 4020;
  public static final int TX_RESTATE = 4021;
  public static final int TX_COLLATERAL_SWAP = 4022;
  public static final int TX_COLLATERAL_SWAP_ADJ = 4023;
  public static final int TX_ADMIN_WITHDRAW_REJECTED = 4024;
  public static final int TX_FROM_BANKRUPT_REMAINDER = 4025;
  public static final int TX_TO_BANKRUPT_REMAINDER = 4026;
  public static final int TX_BALANCE_ADMIN_INVALID_USER_REJECTED = 4027;
  public static final int TX_EXPIRE_SETTLED = 4028;

  public static final int PATCH_DEFAULT = 0;
  public static final int PATCH_FEE_TIER = 1;
  public static final int PATCH_MARGIN_CURVE_ID = 2;

  public static final int CANCEL_ON_REQUEST = 0;
  public static final int CANCEL_ON_DISCONNECT = 1;
  public static final int CANCEL_ON_LOGOUT = 2;

  public static final int DEFAULT_POS_RPT = 0;
  public static final int BALANCE_ADMIN_POS_RPT = 4001;

  // ReusableLogPool
  public static final int POOL_128 = 1; // smaller than 128 bytes
  public static final int POOL_512 = 2; // smaller than 512 bytes
  public static final int POOL_1024 = 3; // smaller than 1024 bytes
  public static final int POOL_LARGE = 4; // larger than 1024 bytes

  // times
  public static final int ONE_SECOND = 1_000;
  public static final int ONE_MINUTE = 60_000;
  public static final int TWO_MINUTE = 120_000;
  public static final int FIVE_MINUTE = 300_000;
  public static final int SIX_MINUTE = 360_000;
  public static final int FIFTEEN_MINUTE = 900_000;
  public static final int ONE_HOUR = 3_600_000;
  public static final int SIX_HOUR = 21_600_000;
  public static final int ONE_DAY = 86_400_000;
  public static final int TWO_DAY = 172_800_000;
  public static final int ONE_WEEK = 604_800_000;

  // logging formats
  public static final String LOG_FMT_1 = "{}";
  public static final String LOG_FMT_2 = "{} {}";
  public static final String LOG_FMT_3 = "{} {} {}";
  public static final String LOG_FMT_4 = "{} {} {} {}";
  public static final String LOG_FMT_5 = "{} {} {} {} {}";
  public static final String LOG_FMT_6 = "{} {} {} {} {} {}";
  public static final String LOG_FMT_7 = "{} {} {} {} {} {} {}";
  public static final String LOG_FMT_8 = "{} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_9 = "{} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_10 = "{} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_11 = "{} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_12 = "{} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_13 = "{} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_14 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_15 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_16 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_17 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_18 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_19 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_20 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_21 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_22 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_23 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_24 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_25 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_26 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_27 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_28 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_29 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_30 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_31 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";
  public static final String LOG_FMT_32 = "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}";

  // String dups

  public static final String GMT = "GMT";
  public static final String LOGLEVEL = "LOG_LEVEL";
  public static final String VALIDATEERROR = "validate error ";
  public static final String FIX44 = "FIX.4.4";
  public static final String ONMATCHER_LIST_EQ = "onMatcher list = ";
  public static final String ONMATCHER_T_EQ = "onMatcher t=";
  public static final String COMA = ", ";
  public static final String IPCPRICINGTOENGINELISTENER_LOADED_LASTSEQUENCENUMBER =
      ">>> IpcPricingToEngineListener loaded lastSequenceNumber=";
  public static final String LASTIPCINDEX_EQ = ", lastIpcIndex=";
  public static final String DATA_EQ = ", data=";
  public static final String LEN_EQ = ", len=";
  public static final String SEQNUM_EQ = ", seqNum=";
  public static final String IPCINDEX_EQ = ", ipcIndex=";
  public static final String PAIRID_EQ = ", pairId=";
  public static final String PRICE_EQ = ", price=";
  public static final String PRICE2_EQ = ", price2=";
  public static final String AVGPX_EQ = ", avgPx=";
  public static final String AVGPXSCALE_EQ = ", avgPxScale=";
  public static final String LASTPX_EQ = ", lastPx=";
  public static final String LASTQTY_EQ = ", lastQty=";
  public static final String STOPPX_EQ = ", stopPx=";
  public static final String TIMEINFORCE_EQ = ", timeInForce=";
  public static final String EXPIRETIME_EQ = ", expireTime=";
  public static final String EXECRESTATEMENTREASON_EQ = ", execRestatementReason=";
  public static final String LASTSEQUENCENUMBER_EQ = ", LASTSEQUENCENUMBER=";
  public static final String POSITIONID_EQ = ", positionId=";
  public static final String POSITION_EQ = ", position=";
  public static final String ABS_POSITION_EQ = ", absPosition=";
  public static final String BASEPOSITIONID_EQ = ", basePositionId=";
  public static final String BASEPOSITIONQUANTITY_EQ = ", basePositionQuantity=";
  public static final String BASEPOSITIONQUANTITYCHANGE_EQ = ", basePositionQuantityChange=";
  public static final String QUOTEDPOSITIONID_EQ = ", quotedPositionId=";
  public static final String QUOTEDPOSITIONQUANTITY_EQ = ", quotedPositionQuantity=";
  public static final String QUOTEDPOSITIONQUANTITYCHANGE_EQ = ", quotedPositionQuantityChange=";
  public static final String PAIR_SETINDEXFEEDUSDMARK_ASSETID = "pair.setIndexFeedUsdMark assetId=";
  public static final String FEEPOSITIONID_EQ = ", feePositionId=";
  public static final String FEEPOSITIONQUANTITY_EQ = ", feePositionQuantity=";
  public static final String FEEPOSITIONQUANTITYCHANGE_EQ = ", feePositionQuantityChange=";
  public static final String UNREALIZEDUSD_EQ = ", unrealizedUsd=";
  public static final String REALIZEDUSD_EQ = ", realizedUsd=";
  public static final String POSITION_TOTAL_EQ = ", positionTotal=";
  public static final String AVGCOSTBASISUSD_EQ = ", avgCostBasisUsd=";
  public static final String QUOTEDUSDMARK_EQ = ", quotedUsdMark=";
  public static final String SETTLECOINUSDMARK_EQ = ", settleCoinUsdMark=";
  public static final String SETTLECOINUNREALIZED_EQ = ", settleCoinUnrealized=";
  public static final String SETTLECOINREALIZED_EQ = ", settleCoinRealized=";
  public static final String SECONDARYORDERID_EQ = ", secondaryOrderId=";
  public static final String INSTRUMENT_SETINDEXFEEDUSDMARK_ASSETID = "instrument.setIndexFeedUsdMark assetId=";
  public static final String MARKETDATABUILDERTHREAD = "MarketDataBuilderThread: ";
  public static final String MESSAGE_EQ = ", msg=";
  public static final String INPUT_OFFSET_EQ = ", inputOffset=";
  public static final String SEQ_EQ = ", seq=";
  public static final String BYTES_EQ = ", bytes=";
  public static final String PUBLISHKAFKA_TOPIC = ">>>msgOut t=";
  public static final String KAFKA_OFFSET_EQ = ", KAFKA_OFFSET=";
  public static final String SEQNUMBYTES_EQ = ", seqNumBytes=";
  public static final String SB_EQ = ", sb=";
  public static final String FEEADMINMESSAGE_ENCODEDLENGTH_EQ = ">>> feeAdminMessage encodedLength=";
  public static final String SECURITYDEFINITION_ENCODEDLENGTH_EQ = ">>> securityDefinition encodedLength=";
  public static final String TRADESTATEADMINMESSAGE_EQ = ", TradeStateAdminMessage=";
  public static final String SENDSTATEADMIN_ENCODEDLENGTH_EQ = ">>> sendStateAdmin encodedLength=";
  public static final String OUTPUTKAFKAOFFSET_EQ = ", outputKafkaOffset=";
  public static final String FEEINSTRUMENT_EQ = ", feeInstrument=";
  public static final String EXECUTIONREPORT_EQ = ", executionReport=";
  public static final String CHANGE_EQ = ", Change=";
  public static final String EXECPUB_GETFEEPOSITIONID_EQ = ">>>>> execPub getFeePositionId=";
  public static final String ADMINMESSAGEBUFFER_EQ = "adminMessageBuffer=";
  public static final String USERADMINMESSAGE_ENCODEDLENGTH_EQ = ">> userAdminMessage encodedLength=";
  public static final String USERID_EQ = ", userId=";
  public static final String CONNECTIONID_EQ = ", connectionId=";
  public static final String FIRMID_EQ = ", firmId=";
  public static final String TXTYPE_EQ = ", txType=";
  public static final String UPDATETYPE_EQ = ", updateType=";
  public static final String USERTYPE_EQ = ", userType=";
  public static final String BALANCETRANSFERTOUSERID_EQ = ", balanceTransferToUserId=";
  public static final String TXID_EQ = ", txId=";
  public static final String SCALE_EQ = ", scale=";
  public static final String MARKVALUE_EQ = ", markValue=";
  public static final String MARKSCALE_EQ = ", markScale=";
  public static final String FEETIER_EQ = ", feeTier=";
  public static final String FEETIERORIG_EQ = ", feeTierOrig=";
  public static final String REQUESTSTATUS_EQ = ", requestStatus=";
  public static final String ROUTETODESTINATION_EQ = ", routeToDestination=";
  public static final String BALANCELIST_EQ = ", balanceList=";
  public static final String SOURCESEQNUM_EQ = ", sourceSeqNum=";
  public static final String TARGETSTRATEGY_EQ = ", targetStrategy=";
  public static final String ISHIDDEN_EQ = ", isHidden=";
  public static final String ISLIQUIDATION_EQ = ", isLiquidation=";
  public static final String ISLASTLOOK_EQ = ", isLastLook=";
  public static final String FEEESTIMATEDQUANTITY_EQ = ", feeEstimatedQuantity=";
  public static final String FEEACCUMULATEDQUANTITY_EQ = ", feeAccumulatedQuantity=";
  public static final String AVAILABLEESTIMATEDQUANTITY_EQ = ", availableEstimatedQuantity=";
  public static final String AVAILABLEACCUMULATEDQUANTITY_EQ = ", availableAccumulatedQuantity=";
  public static final String SOURCESENDTIME_EQ = ", sourceSendTime=";
  public static final String TOKENID_EQ = ", tokenId=";
  public static final String SELECTID_EQ = ", selectId=";
  public static final String QUOTETYPE_EQ = ", quoteType=";
  public static final String QUOTE_TARGET_USERID_EQ = ", quoteTargetUserId=";
  public static final String ENABLESTATEVALIDATOR_EQ = ", enableStateValidator=";
  public static final String TIMESTAMP_EQ = ", timestamp=";
  public static final String TRIGGERTIMEMILLIS_EQ = ", triggerTimeMillis=";
  public static final String BALANCEADMINMESSAGE_SENDERCOMPID_EQ = "BalanceAdminMessage [senderCompId=";
  public static final String PUBLISH_BALANCEADMINMESSAGE_EQ = ">> publish balanceAdminMessage=";
  public static final String INSTRUMENT_EQ = ", instrument=";
  public static final String POSITIONARR_EQ = ", positionArr=";
  public static final String USDCOLLATERALVALUE_EQ = ", usdCollateralValue=";
  public static final String USDCOLLATERALVALUEDISCOUNTED_EQ = ", usdCollateralValueDiscounted=";
  public static final String TOTALCOUNT_EQ = ", totalcount=";
  public static final String REJECT_ORDER_EQ = ">>> reject order ";
  public static final String ORDER_EQ = ", order=";
  public static final String UNKNOWN_ORDER_CANCELORDER_EQ = "createCancelReject UNKNOWN_ORDER cancelOrder=";
  public static final String QUANTITYFILLED_EQ = ", quantityFilled=";
  public static final String COUNTERPARTYUSER_EQ = ", counterpartyUser=";
  public static final String INSTR_EQ = ", instr=";
  public static final String MAP_EQ = ", map=";
  public static final String LIQUIDATIONORDER_EQ = ", liquidationOrder=";
  public static final String FOUND_COUNTERPARTYPOSITION_EQ = ", found counterpartyPosition=";
  public static final String USER_GETUSDVALUE_EQ = ", user.getUsdValue()=";
  public static final String ISMARGINLIQUIDATIONSATISFIED_MARGINRATIO_EQ = ">> isMarginLiquidationSatisfied marginRatio=";
  public static final String ISMARGINLIQUIDATIONSATISFIED2_MARGINRATIO_EQ = ">> isMarginLiquidationSatisfied2 marginRatio=";
  public static final String LIQUIDATIONORDER_POSITION_CHANGED_EQ = "liquidationOrder position changed=";
  public static final String ADDORDERDR_ID_EQ = "addOrderDR id=";
  public static final String CANCELORDERDR_ID_EQ = "cancelOrderDR id=";
  public static final String CANCELORDER_EQ = ", cancelOrder=";
  public static final String UPDATEORDERFROMEXECREPORT_ID_EQ = "updateOrderFromExecReport id=";
  public static final String VALUE_EQ = ", value=";
  public static final String PAIR_EQ = ", pair=";
  public static final String BIDS_EQ = ", bids=";
  public static final String ASKS_EQ = ", asks=";
  public static final String BIDSCOUNT_EQ = ", bidsCount=";
  public static final String ASKSCOUNT_EQ = ", asksCount=";
  public static final String BIDSQUANTITY_EQ = ", bidsQuantity=";
  public static final String ASKSQUANTITY_EQ = ", asksQuantity=";
  public static final String BIDSNOTIONAL_EQ = ", bidsNotional=";
  public static final String ASKSNOTIONAL_EQ = ", asksNotional=";
  public static final String MAXNOTIONAL_EQ = ", maxNotional=";
  public static final String FEEQTY_EQ = ", feeQty=";
  public static final String QTYINORDERBOOK_EQ = ", qtyInOrderbook=";
  public static final String ISPAIDTPINSURANCE_EQ = ", isPaidToInsurance=";
  public static final String EXECTYPE_EQ = ", execType=";
  public static final String SECONDARYEXECID_EQ = ", secondaryExecId=";
  public static final String ORDER_SECURITYID_EQ = "Order [securityId=";
  public static final String DREXECUTIONREPORT_SECURITYID_EQ = "DRExecutionReport [securityId=";
  public static final String OPENORDERREQUIREDMARGIN_EQ = ", openOrderRequiredMargin=";
  public static final String POSITIONREQUIREDMARGIN_EQ = ", positionRequiredMargin=";
  public static final String USEROPENORDERSBYPAIR_USER_EQ = "UserOpenOrdersByPair [user=";
  public static final String UPDATEORDERFROMEXECREPORT_FEEID_EQ = "updateOrderFromExecReport, feeId=";
  public static final String KAFKAINPUTFIXLISTENER_TOPIC_EQ = ">>> KafkaInputFixListener topic=";
  public static final String LOADED_LASTSEQUENCENUMBER_EQ = ", loaded lastSequenceNumber=";
  public static final String INPUTTIME_EQ = ", inTime=";
  public static final String DECODEDTIME_EQ = ", decodedTime=";
  public static final String MATCHTIME_EQ = ", matchTime=";
  public static final String MESSAGETYPE_EQ = ", messageType=";
  public static final String MSGTYPE_EQ = ", msgType=";
  public static final String LATENCY_EQ = ", latency=";
  public static final String SENDTIME_EQ = ", sendTime=";
  public static final String RECORDOFFSET_EQ = ", recordOffset=";
  public static final String RECEIVED_SEQNUM_EQ = "received: seqNum=";
  public static final String LENGTH_EQ = ", length=";
  public static final String HEADERDECODER_EQ = ", headerDecoder";
  public static final String SENDERCOMPID_EQ = ", senderCompId=";
  public static final String TARGETCOMPID_EQ = ", targetCompID=";
  public static final String DECODED_MESSAGE_EQ = "decoded message=";
  public static final String ORIGMESSAGE_EQ = " origMessage=";
  public static final String SEND_TIME_EQ = ", sendTime=";
  public static final String POSITIONS_EQ = "[positions=";
  public static final String USER_ID_EQ = "User [id=";
  public static final String LOGIN_EQ = ", login=";
  public static final String VERIFICATION_EQ = ", verification=";
  public static final String USDVALUE_EQ = ", usdValue=";
  public static final String USDNOTIONALPOSITIONVALUE_EQ = ", usdNotionalPositionValue=";
  public static final String USDOPENORDERSVALUE_EQ = ", usdOpenOrdersValue=";
  public static final String USDOPENORDERSREQUIREDVALUE_EQ = ", usdOpenOrdersRequiredValue=";
  public static final String USDMARGINVALUE_EQ = ", usdMarginValue=";
  public static final String USDMARGINREQUIREDVALUE_EQ = ", usdMarginRequiredValue=";
  public static final String USDMARGINABLEVALUE_EQ = ", usdMarginableValue=";
  public static final String USDMARGINMAINTVALUE_EQ = ", usdMarginMaintValue=";

  public static final String LEVERAGERATIO_EQ = ", leverageRatio=";
  public static final String MARGINRATIO_EQ = ", marginRatio=";
  public static final String MARGINCURVEIDOVERRIDE_EQ = ", marginCurveIdOverride=";

  public static final String USDUNREALIZED_EQ = ", usdUnrealized=";
  public static final String LASTLIQUIDATIONTIME_EQ = ", lastLiquidationTime=";
  public static final String AUTOLIQUIDATIONSTATE_EQ = ", autoLiquidationState=";
  public static final String COLLATERALSWAPSTATE_EQ = ", collateralSwapState=";
  public static final String MARKETDATASNAPMESSAGE_INSTRUMENTPAIR_EQ = "MarketDataSnapMessage [instrumentPair=";
  public static final String POSITIONREPORTMESSAGE_USER_EQ = "PositionReportMessage user=";
  public static final String ACK_ADMIN_MESSAGE_RECEIVED = "Ack Admin Message Received";
  public static final String USER_ADMIN_MESSAGE_RECEIVED = "User Admin Message Received";
  public static final String BALANCE_ADMIN_MESSAGE_RECEIVED = "Balance Admin Message Received";
  public static final String FEE_ADMIN_MESSAGE_RECEIVED = "Fee Admin Message Received";
  public static final String SECURITY_DEFINITION_ADMIN_MESSAGE_RECEIVED = "Security Definition Admin Message Received";
  public static final String TRADE_STATE_MESSAGE_RECEIVED = "Trade State Message Received";
  public static final String FIX_USER_ADMIN_MESSAGE_RECEIVED = "FIX User Admin Message Received";
  public static final String FUNDINGRATECALC_MESSAGE_RECEIVED = "FundingRateCalc Message Received";
  public static final String GLOBALSTATEADMIN_MESSAGE_RECEIVED = "GlobalStateAdmin Message Received";
  public static final String SNAPRESPONSEADMINMESSAGE_MESSAGE_RECEIVED = "SnapResponseAdminMessage Message Received";
  public static final String KAFKA_ADMIN_DECODED_ADMIN_MESSAGE_EQ = "Kafka admin decoded admin message=";
  public static final String SNAPLOADERMODE_EQ = ", snapLoaderMode=";
  public static final String USERNAME_EQ = ", username=";
  public static final String MESSAGEHEADERDECODER_EQ = "messageHeaderDecoder=";
  public static final String HANDLEADMINMESSAGE_TEMPLATEID_EQ = ">>> handleAdminMessage, templateId=";
  public static final String RECEIVED_BUFFER_EQ = "received buffer=";
  public static final String HANDLEMESSAGE_MSGSEQNUM_EQ = ">>>msgIn msgSeqNum=";
  public static final String MARKET_DATA_RECEIVED = "Market Data Received";
  public static final String NEW_ORDER_SINGLE_RECEIVED = "New Order Single Received";
  public static final String ORDER_CANCEL_REQUEST = "Order Cancel Request";
  public static final String ORDER_CANCEL_REPLACE = "Order Cancel Replace";
  public static final String ASSET_GROUP_REQUEST = "Asset Group Request";
  public static final String ORDER_MASS_CANCEL_REPLACE = "Order Mass Cancel Replace";
  public static final String MARKET_DATA_FEED = "Market Data Feed";
  public static final String LOGON_MESSAGE_RECEIVED = "Logon Message Received, senderCompId=";
  public static final String LOGOUT_MESSAGE_RECEIVED = "Logout Message Received";
  public static final String HEARTBEAT_MESSAGE_RECEIVED = "Heartbeat Message Received";
  public static final String RESEND_REQUEST_MESSAGE_RECEIVED = "Resend Request Message Received";
  public static final String SEQUENCE_RESET_MESSAGE_RECEIVED = "Sequence Reset Message Received";
  public static final String UNABLE_TO_DECODE_MSGTYPE = "unable to decode msgType=";
  public static final String ROUNDROBINLOCKID_EQ = ", roundRobinLockId=";
  public static final String ONPUBLISH_ROUNDROBINID_EQ = "onPublish roundRobinId=";
  public static final String ROUNDROBINID_EQ = ", roundRobinId=";
  public static final String CURRENTTIME_EQ = ", currentTime=";
  public static final String TRIGGERTIME_EQ = ", triggerTime=";
  public static final String FUNDINGRATECALCMESSAGE_UPDATETYPE_EQ = "FundingRateCalcMessage, updateType=";
  public static final String ADMINMESSAGE_EQ = ", adminMessage=";
  public static final String LIQUIDATIONMODE_EQ = ", liquidationMode=";
  public static final String USEINSURANCE_EQ = ", useInsurance=";
  public static final String PARSE_CANCELREPLACEORDER = ">>> parse CancelReplaceOrder";
  public static final String COLLECTINGUSER_EQ = ", collectingUser=";
  public static final String ISPAIDTOINSURANCE_EQ = ISPAIDTPINSURANCE_EQ;
  public static final String TRANSFERTOEXCHANGE_FEEID_EQ = "transferToExchange: feeId=";
  public static final String ADDBALANCE_BALANCEADMINMESSAGE_EQ = ">> addBalance balanceAdminMessage=";
  public static final String USER_EQ = ", user=";
  public static final String FEEINSTRUMENTID_EQ = ", feeInstrumentId=";
  public static final String FEE_EQ = ", fee=";
  public static final String FEETYPE_EQ = ", feeType=";
  public static final String TIER_EQ = ", tier=";
  public static final String EXTERNALID_EQ = ", externalId=";
  public static final String MAKERTAKER_EQ = ", makerTaker=";
  public static final String SECURITYID_EQ = ", securityId=";
  public static final String SYMBOL_EQ = ", symbol=";
  public static final String NAME_EQ = ", name=";
  public static final String ASSETTYPE_EQ = ", assetType=";
  public static final String MARKETSTATUS_EQ = ", marketStatus=";
  public static final String BASEID_EQ = ", baseId=";
  public static final String QUOTEID_EQ = ", quotedId=";
  public static final String PRICESCALE_EQ = ", priceScale=";
  public static final String PRICE_SCALE_EQ = ", price_scale=";
  public static final String PRICE2_SCALE_EQ = ", price2_scale=";
  public static final String MARKETTYPE_EQ = ", marketType=";

  public static final String QUANTITYSCALE_EQ = ", quantityScale=";
  public static final String BASE_EQ = ", base=";
  public static final String QUOTED_EQ = ", quoted=";
  public static final String QTY_EQ = ", qty=";
  public static final String QTY_SCALE_EQ = ", qty_scale=";
  public static final String ORDERPRIORITY_EQ = ", orderPriority=";
  public static final String TYPE_EQ = ", type=";
  public static final String CANCELID_EQ = ", cancelId=";
  public static final String CANCELPRIORITY_EQ = ", cancelPriority=";
  public static final String STOPPX_SCALE_EQ = ", stopPx_scale=";
  public static final String STOPTRIGGEREDORDER_EQ = ", stop triggered, order=";
  public static final String STOPPX_INT_EQ = ", stopPxInt=";
  public static final String TO_CLOSE_EQ = ", toClose=";
  public static final String PRICEINT_EQ = ", priceInt=";
  public static final String QUANTITYLONG_EQ = ", quantityLong=";
  public static final String QUANTITYORIGLONG_EQ = ", quantityOrigLong=";
  public static final String QUANTITYORIGLONGSCALE_EQ = ", quantityOrig_scale=";
  public static final String SENDERCOMPIDASSTRING_EQ = ", senderCompIdAsString=";
  public static final String SENDERCOMPIDCHARARR_EQ = ", senderCompIdCharArr=";
  public static final String MARGINCHECKREFERENCEPRICE_EQ = ", marginCheckReferencePrice=";
  public static final String ORDERBOOKSTRATEGY_EQ = ", orderBookStrategy=";
  public static final String PREORDERCHECKSTRATEGY_EQ = ", preOrderCheckStrategy=";
  public static final String ESTIMATEDUSERCOUNT_EQ = ", estimatedUserCount=";
  public static final String DAYSFEEDISACTIVE_EQ = ", daysFeedIsActive=";
  public static final String ESTIMATEDVOLATILITY_EQ = ", estimatedVolatility=";
  public static final String ESTIMATEDVAR_EQ = ", estimatedVAR=";
  public static final String SETTLETYPE_EQ = ", settleType=";
  public static final String MINQTY_EQ = ", minQty=";
  public static final String MAXQTY_EQ = ", maxQty=";
  public static final String MAXPRICE_EQ = ", maxPrice=";
  public static final String PRICE2INT_EQ = ", price2Int=";
  public static final String MASSCANCELORDER_SECURITYID_EQ = "MassCancelOrder [securityId=";
  public static final String MARKET_DATA_FEED_EQ = "MarketDataFeed [sentTime=";
  public static final String CANCELORDER_SECURITYID_EQ = "CancelOrder [securityId=";
  public static final String CANCELREPLACEORDER_SECURITYID_EQ = "CancelReplaceOrder [securityId=";
  public static final String SUPPORTORDERTYPE_EQ = ", supportOrderType=";
  public static final String MARGINCURVEID_EQ = ", marginCurveId=";
  public static final String COMISSIONTYPE_EQ = ", commissionType=";
  public static final String INDEXFEEDUSDMARK_EQ = ", indexFeedUsdMark=";
  public static final String CACHEDEPTH_EQ = ", cacheDepth=";
  public static final String AUCTION_START_TIME_HR_GMT_EQ = ", auctionStartTimeHrGMT=";
  public static final String AUCTION_DURATION_TIME_EQ = ", auctionDurationTime=";
  public static final String AUCTION_FIXING_ATTEMPTS_EQ = ", auctionFixingAttempts=";
  public static final String AUCTION_FIXING_WAIT_TIME_EQ = ", auctionFixingWaitTime=";
  public static final String PYSICALSETTLE_EQ = ", physicalSettle=";
  public static final String LIMIT_ONLY_MODE_EQ = ", limitOnlyMode=";
  public static final String TEXTDATA_EQ = ", textData=";
  public static final String STATUS_EQ = ", status=";
  public static final String ACCOUNTTYPE_EQ = ", accountType=";
  public static final String LMM_EQ = ", lmm=";
  public static final String TEXT_EQ = ", text=";
  public static final String ORDERID_EQ = ", orderId=";
  public static final String ORIGORDERID_EQ = ", origOrderId=";
  public static final String MARKETDATAFEED_EQ = ", marketDataFeed=";
  public static final String REFMSGTYPE_EQ = ", refMsgType=";
  public static final String SIDE_EQ = ", side=";
  public static final String ORDTYPE_EQ = ", ordType=";
  public static final String ACCOUNT_EQ = ", account=";
  public static final String SUBMITTERID_EQ = ", submitterId=";
  public static final String EXECID_EQ = ", execId=";
  public static final String ORDSTATUS_EQ = ", ordStatus=";
  public static final String CXLREJREASON_EQ = ", cxlRejReason=";
  public static final String CLORID_EQ = ", clOrdId=";
  public static final String LEAVESQTY_EQ = ", leavesQty=";
  public static final String ORDERQTY_EQ = ", orderQty=";
  public static final String CUMQTY_EQ = ", cumQty=";
  public static final String BUSINESSREJECTREFID_EQ = ", businessRejectRefID=";
  public static final String USERADMINMESSAGE_SENDERCOMPID_EQ = "UserAdminMessage [senderCompId=";
  public static final String CANCELREJECTMESSAGE_CLORDID_EQ = "CancelRejectMessage [clOrdId=";
  public static final String OPTIONPRICINGMESSAGE_MSGSEQ_EQ = "OptionPricingMessage [messageSequenceNumber=";

  public static final String EXECUTIONREPORTMESSAGE_SECURITYID_EQ = "ExecutionReportMessage [securityId=";
  public static final String BUSINESSREJECTMESSAGE_BUSINESSREJECTREASON_EQ = "BusinessRejectMessage [businessRejectReason=";
  public static final String USEDISCOUNTFEESCOIN_EQ = ", useDiscountFeesCoin=";
  public static final String SECURITYDEFINITIONADMINMESSAGE_UPDATETYPE_EQ = "SecurityDefinitionAdminMessage [updateType=";
  public static final String COLLATERALMARGINPERCENTDISCOUNT_EQ = ", collateralMarginPercentDiscount=";
  public static final String ARRSIZE_EQ = ", arrSize=";
  public static final String MAINTMARGINPERCENT_EQ = ", maintMarginPercent=";
  public static final String REQUIREDMARGINPERCENT_EQ = ", requiredMarginPercent=";
  public static final String INSURANCELOSSPERCENTLIMIT_EQ = ", insuranceLossPercentLimit=";
  public static final String INSURANCEPOSITIONPERCENTLIMIT_EQ = ", insurancePositonPercentLimit=";
  public static final String ORDERSEQUENCENUMBER_EQ = ", orderSequenceNumber=";
  public static final String EXECSEQUENCENUMBER_EQ = ", execSequenceNumber=";
  public static final String INSURANCEAUTOCLOSEMODE_EQ = ", insuranceAutoCloseMode=";
  public static final String DISCOUNTFEESCOINBASISPTS_EQ = ", discountFeesCoinBasisPts=";
  public static final String FEEADMINMESSAGE_SENDERCOMPID_EQ = "FeeAdminMessage [senderCompId=";
  public static final String COLLATERALSWAPMESSAGE_UPDATETYPE_EQ = "CollateralSwapMessage [updateType=";
  public static final String RESTATEALLUSERS_USERADMINMESSAGE_EQ = "restateAllUsers userAdminMessage=";
  public static final String RESTATEALL_ASSET_GROUPS_EQ = "restateAllAssetGroups assetGroup=";
  public static final String RESTATEALLUSERS_BALANCEADMINMESSAGE_EQ = "restateAllUserPositions balanceAdminMessage=";
  public static final String POSITIONSGROUPENCODER_EQ = ", positionsGroupEncoder=";
  public static final String POSITIONREPORTMESSAGE_EQ = ", positionReportMessage=";
  public static final String ORDERTAKER_EQ = ", orderTaker=";
  public static final String ORDERMAKER_EQ = ", orderMaker=";
  public static final String POSITIONARR_I_EQ = ", positionArr[i]=";
  public static final String ASSETID_EQ = ", assetId=";
  public static final String GROUPASSETID_EQ = ", groupAssetId=";
  public static final String VERBOSE_AUTOLIQUIDATE_MARGIN_CALL_TRIGGERED_USER_EQ = ">>> verbose autoLiquidate margin call triggered user=";
  public static final String VERBOSE_AUTOLIQUIDATE_MARGIN_CALL_TRIGGERED_USER2_EQ =
      ">>> verbose autoLiquidate margin call triggered user2=";
  public static final String VERBOSE_AUTOLIQUIDATE_MARGIN_CALL_TRIGGERED_USER3_EQ =
      ">>> verbose autoLiquidate margin call triggered user3=";
  public static final String EXECREPORT_EQ = ", execReport=";
  public static final String REFERENCEPRICE_EQ = ", referencePrice=";
  public static final String REFERENCEQUANTITY_EQ = ", referenceQuantity=";
  public static final String UPDATEFILLSELL_ORDER_EQ = ">>> updateFillSell order=";
  public static final String UPDATEFILLPHYSICALSELL_ORDER_EQ = ">>> updateFillPhysicalSell order=";
  public static final String UPDATEFILLPHYSICALBUY_ORDER_EQ = ">>> updateFillPhysicalBuy order=";
  public static final String USD_FEE_EQ = ", usdFee=";
  public static final String FEEQUANTITY_EQ = ", feeQuantity=";
  public static final String FEEMARK_EQ = ", feeMark=";
  public static final String UPDATEFILL_FEE_CALC_USDNOTIONAL_EQ = ">>> updateFill fee calc usdNotional=";
  public static final String POSITIONREPORTENCODER_EQ = ", positionReportEncoder=";
  public static final String USER18PUBLISH2_EXECUTIONREPORT_EQ = ">>> 18publish2 executionReport=";
  public static final String NULL = "null";
  public static final String INSTRUMENT_PAIR_EQ = ", instrumentPair=";
  public static final String QUANTITY_EQ = ", quantity=";
  public static final String MARK_EQ = ", mark=";
  public static final String MAINT_MARGIN_EQ = ", maintMargin=";
  public static final String REQUIRED_MARGIN_EQ = ", requiredMargin=";
  public static final String ABSNOTIONAL_EQ = ", absNotional=";
  public static final String UNREALIZED_EQ = ", unrealized=";
  public static final String RISK_USER_EQ = " risk user=";
  public static final String USDNOTIONAL_EQ = ", usdNotional=";
  public static final String ADJREFERENCEQUANTITY_EQ = ", adjReferenceQuantity=";
  public static final String TRADEPNL_EQ = ", tradePnl=";
  public static final String SETTLEQUANTITYCHANGE_EQ = ", settleQuantityChange=";
  public static final String FEEPOSITION_EQ = ", feePosition=";
  public static final String DIFF_EQ = ", diff=";
  public static final String GETQUANTITYLONG_EQ = ", GETQUANTITYLONG=";
  public static final String OPENORDERCOUNT_EQ = ", OpenOrderCount=";
  public static final String USEROPENORDERSBYPAIR_EQ = ", userOpenOrdersByPair=";
  public static final String USER_GETFEETIER_EQ = ", user.getFeeTier()=";
  public static final String USDMARK_EQ = ", usdMark=";
  public static final String USDNOTIONALLONG_EQ = ", usdNotionalLong=";
  public static final String NEWAVGCOSTBASIS_EQ = ", newAvgCostBasis=";
  public static final String NORMALIZED_EQ = ", normalized=";
  public static final String D_SETTLEQUANTITYCHANGE_EQ = ", d-settleQuantityChange=";
  public static final String TOTALREFQTYCOSTBASISLONG_EQ = ", totalRefQtyCostBasisLong=";
  public static final String TOTALORIGCOSTBASIS_EQ = ", totalOrigCostBasis=";
  public static final String ORIGPOSITIONQUANTITY_EQ = ", origPositionQuantity=";
  public static final String NEWAVGCOSTBASISLONG_EQ = ", newAvgCostBasisLong=";
  public static final String PAIRPOSITION_GETUSDAVGCOSTBASIS_EQ = ", pairPosition.getUsdAvgCostBasis()=";
  public static final String UPDATEFILL_SELL_ORDER_EQ = ">>> updateFill SELL order=";
  public static final String UPDATEFILL_BUY_ORDER_EQ = ">>> updateFillBuy order=";
  public static final String UPDATEFILL_SELL_TO_CLOSE_ORDER_EQ = ">>> updateFill sell to close order=";
  public static final String TRADEPNLLONG_EQ = ", tradePnlLong=";
  public static final String SETTLECOINUSDMARKLONG_EQ = ", settleCoinUsdMarkLong=";
  public static final String D_SETTLECOINREALIZED_EQ = ", d-settleCoinRealized=";
  public static final String SETTLEQUANTITYCHANGEREALIZEDLONG_EQ = ", settleQuantityChangeRealizedLong=";
  public static final String CHECKORDER2_REQUIREDMARGINCHANGE_EQ = ">>> CHECKORDER2_REQUIREDMARGINCHANGE_EQ=";
  public static final String VERBOSE_UPDATERISK_EQ = ">>> verbose updateRisk";
  public static final String INSTRUMENTPAIR_MARK_EQ = " instrumentPair mark=";
  public static final String DECODED_EXECUTIONREPORT_EQ = "decoded executionReport=";
  public static final String DECODED_POSITIONREPORT_EQ = "decoded positionReport=";
  public static final String DECODED_ASSETGROUP_EQ = "decoded assetGroup=";

  public static final String LOCKID_EQ = ", lockId=";
  public static final String MSGSEQNUM_EQ = ", msgSeqNum=";
  public static final String KAFKARECORDOFFSET_EQ = ", kafkaRecordOffset=";
  public static final String HEADER_EQ = ", header=";
  public static final String DECODE_ERROR_MSGTYPE_EQ = "decode error, msgType=";
  public static final String NEXTID_EQ = ", nextId=";
  public static final String DIR_EQ = ", dir=";
  public static final String TARGET_EQ = ", target=";
  public static final String MESSAGECOUNT_EQ = ", messageCount=";
  public static final String TOSTRING_EQ = ", toString()=";
  public static final String UNDERLYERID_EQ = ", underlyerId=";
  public static final String STRIKEPRICE_EQ = ", strikePrice=";
  public static final String USDSTRIKEPRICE_EQ = ", usdStrikePrice=";
  public static final String USDUNDERLYERPRICE_EQ = ", usdUnderlyerPrice=";
  public static final String USDMODELPRICE_EQ = ", usdModelPrice=";
  public static final String INTERESTRATE_EQ = ", interestRate=";
  public static final String TIMETOEXPIRE_EQ = ", timeToExpire=";
  public static final String DIVIDEND_EQ = ", dividend=";
  public static final String DELTA_EQ = ", delta=";
  public static final String THETA_EQ = ", theta=";
  public static final String RHO_EQ = ", rho=";
  public static final String NORMALCDF_EQ = ", normalCDF=";
  public static final String GAMMA_EQ = ", gamma=";
  public static final String VEGA_EQ = ", vega=";
  public static final String SIGMA_EQ = ", sigma=";
  public static final String BID_EQ = ", bid=";
  public static final String ASK_EQ = ", ask=";
  public static final String LAST_EQ = ", last=";
  public static final String OPENQTY_EQ = ", openQty=";

  public static final String EXPIRETIMEMILLIS_EQ = ", expireTimeMillis=";
  public static final String DECODEFIXUSERADMINUPDATE_EQ = ">>> decodeFIXUserAdminUpdate";
  public static final String DECODESNAPRESPONSEADMIN_EQ = ">>> decodeSnapResponseAdmin";
  public static final String DECODEGLOBALSTATEADMINUPDATE_EQ = ">>> decodeGlobalStateAdminUpdate";
  public static final String DECODEFUNDINGRATECALCADMINUPDATE_EQ = ">>> decodeFundingRateCalcAdminUpdate";
  public static final String DECODETRADESTATEADMINUPDATE_EQ = ">>> decodeTradeStateAdminUpdate";
  public static final String DECODESECURITYDEFINITIONADMINUPDATE_EQ = ">>> decodeSecurityDefinitionAdminUpdate";
  public static final String DECODEFEEADMINUPDATE_EQ = ">>> decodeFeeAdminUpdate";
  public static final String DECODEBALANCEADMINUSERUPDATE_EQ = ">>> decodeBalanceAdminUserUpdate";
  public static final String DECODEADMINUSERUPDATE_EQ = ">>> decodeAdminUserUpdate";

  public static final String FAILOVER_ALL_MESSAGES_READ = "All messages read from output queue upto failover point.";
  public static final String FAILOVER_MESSAGE_RECEIVED = "Failover message received. Setting new receiver instance ID.";
  public static final String INVALID_SENDER_INSTANCE_ID = "Invalid sender instance id. Ignoring the message.";
  public static final String CURRENT_EQ = ", current=";
  public static final String NEW_EQ = ", new=";
  public static final String ISCOLLATERALSWAPENABLED_EQ = ", isCollateralSwapEnabled=";
  public static final String OPERATION_UNSUPPORTED_ON = "Operation unsupported on ";
  public static final String CONTROLLER = " controller";
  public static final String PRIORITY = "priority";
  public static final String BIDLEVELCACHEPTRARR0_EQ = ", bidLevelCachePtrArr[0]=";
  public static final String ASKLEVELCACHEPTRARR0_EQ = ", askLevelCachePtrArr[0]=";
  public static final String MATCHONASKS_CROSS_EQ = "matchOnAsks cross=";
  public static final String MAKERORDER_EQ = ", makerOrder=";
  public static final String TAKERORDER_EQ = ", takerOrder=";
  public static final String MAKERORDERUSER_EQ = ", makerOrderUser=";
  public static final String TAKERORDERUSER_EQ = ", takerOrderUser=";
  public static final String NULL_FOUND = "NULL FOUND";
  public static final String T0_EQ = ", t0=";
  public static final String LIQUIDATON_MODE_EQ = ", isLIQUIDATON_MODE=";
  public static final String ISBTCUSDTFUTURERECEIVED_EQ = ", isBTCUSDTFutureReceived=";
  public static final String ISBTCUSDCFUTURERECEIVED_EQ = ", isBTCUSDCFutureReceived=";
  public static final String REMOVE_BUY_ORDER_EQ = "removeBuyOrder=";
  public static final String REMOVE_SELL_ORDER_EQ = "removeSellOrder=";
  public static final String ONPERSIST_MESSAGE_EQ = "onPersist message=";
  public static final String REDUCE_ONLY_EQ = ">> REDUCE_ONLY reducing, order=";
  public static final String WITHDRAW_FEE_EQ = ", withdrawFee=";
  public static final String IS_WITHDRAW_FEE_PERCENT_EQ = ", isWithdrawFeePercent=";
  public static final String WITHDRAW_FEE_INSTRUMENT_EQ = ", withdrawFeeInstrument=";

}
