package com.solfini.common;

/**
 * 
 * @author Chris Mack
 *
 */
public enum MessageType {

  //@formatter:off
  NEW_ORDER, CANCEL_ORDER, EXECUTION_REPORT, OPTION_PRICING, LOGON,LOGOUT, HEARTBEAT, RESEND_REQUEST, SEQUENCE_RESET, POSITION_REPORT, MASS_CANCEL_ORDER, LIQUIDATION_ORDER, MARKET_DATA_FEED, ASSET_GROUP,
  BALANCE_ADMIN, FEE_ADMIN, TRADE_STATE_ADMIN,
  CANCEL_REJECT, BUSINESS_REJECT, USER_ADMIN, FIX_USER_ADMIN, SECURITY_DEFINITION, ACK_ADMIN, MARKET_DATA_SNAP, FUNDING_RATE_CALC, EXPIRE_CALC, ADDRESS_STATE, SNAP_RESPONSE, GLOBAL_STATE_ADMIN, COLLATERAL_SWAP,
  MODE_CONTROL, SHUTDOWN_CONTROL, PUBLISH_CONTROL, COPY_TRADE, INFLUENCER_SUBSCRIPTION
  //@formatter:on

}
