INSTANCE_ID=stg-me02

FIX_HOST=127.0.0.1
FIX_PORT=44999
STREAM_ID=1

INBOUND_THREAD_IDLE=NoOpIdleStrategy
MATCHING_THREAD_IDLE=NoOpIdleStrategy
PUBLISHER_THREAD_IDLE=NoOpIdleStrategy
PERSIST_THREAD_IDLE=NoOpIdleStrategy
RISK_THREAD_IDLE=NoOpIdleStrategy

QUEUE_CAPACITY=8388608
LOGGING_QUEUE_CAPACITY=25000000

MARKET_STATUS=5
DB_URL=jdbc:postgresql://34.239.220.159:5432/wildfly
DB_USER=bijiedev
DB_PASSWORD=Csap2012

CHRONICLE_ENGINE_OUTPUT_DIRECTORY=/mnt/chronicle/engine-output  
CHRONICLE_ENGINE_DR_INPUT_DIRECTORY=/mnt/chronicle/engine-output
CHRONICLE_PRICING_OUTPUT_DIRECTORY=/mnt/chronicle/pricing-output
CHRONICLE_API_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-to-engine
CHRONICLE_API_ADMIN_TO_ENGINE_DIRECTORY=/mnt/chronicle/api-admin-to-engine
CHRONICLE_MARKET_MAKER_TO_ENGINE_DIRECTORY=/mnt/chronicle/market-maker-to-engine
CHRONICLE_ENGINE_BALANCE_DIRECTORY=/mnt/chronicle/engine-balance
CHRONICLE_ENGINE_SNAP_DIRECTORY=/efs/snap

MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/execution-report
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order
MM_ORDER_BOOK_INDEX_DIRECTORY=/mnt/mm/order-book-index
MM_EXECUTION_REPORT_DIRECTORY=/mnt/mm/order-book-map
MM_USER_ORDER_INDEX_DIRECTORY=/mnt/mm/user-order-index
MM_BALANCE_DIRECTORY=/mnt/mm/balance
MM_BALANCE_HISTORY_DIRECTORY=/mnt/reports/balance-history

ACK_REJECT_MESSAGES=true
PUBLISH_MARKET_DATA=false
INITIAL_USER_CACHE_SIZE=1048576

ME_KAFKA_TOPIC_PRIMARY=me10000009f
ME_KAFKA_TOPIC_SECONDARY=me10000009f_dr
API_KAFKA_TOPIC_IN=api9f

LOAD_FROM_SNAP=1568785313769305202
LOAD_FROM_SNAP_AND_REPLAY=OUTPUT

CONTROLLER_TYPE=unified
CONTROLLER_MODE=secondary
CONTROLLER_ZOOKEEPER_LOCATION=172.31.66.209:2181
CONTROLLER_ZOOKEEPER_PRIORITY=0

KAFKA.CONSUMER.bootstrap.servers=172.31.66.209:4455
KAFKA.CONSUMER.group.id=matching-engine-02
KAFKA.CONSUMER.enable.auto.commit=true
KAFKA.CONSUMER.auto.commit.interval.ms=10
KAFKA.CONSUMER.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
KAFKA.CONSUMER.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
KAFKA.CONSUMER.session.timeout.ms=10000
KAFKA.CONSUMER.receive.buffer.bytes=262144
KAFKA.CONSUMER.max.partition.fetch.bytes=2097152

KAFKA.PRODUCER.bootstrap.servers=172.31.66.209:4455
KAFKA.PRODUCER.acks=all
KAFKA.PRODUCER.retries=0
KAFKA.PRODUCER.batch.size=16384
KAFKA.PRODUCER.auto.commit.interval.ms=10
KAFKA.PRODUCER.linger.ms=0
KAFKA.PRODUCER.key.serializer=org.apache.kafka.common.serialization.StringSerializer
KAFKA.PRODUCER.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
KAFKA.PRODUCER.block.on.buffer.full=true
KAFKA.PRODUCER.compression.type=snappy

PUBLISH_HEALTH_REPORT_MAIL=false

AUTOMATIC_LOG_DISABLE_ON_LATENCY=false
MAX_LATENCY_FOR_LOG_DISABLE_MS=1000
MIN_LATENCY_FOR_LOG_ENABLE_MS=500
