// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicSpotKlineV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicSpotKlineV3ApiProto {
  private PublicSpotKlineV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicSpotKlineV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicSpotKlineV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032PublicSpotKlineV3Api.proto\"\307\001\n\024PublicS" +
      "potKlineV3Api\022\020\n\010interval\030\001 \001(\t\022\023\n\013windo" +
      "wStart\030\002 \001(\003\022\024\n\014openingPrice\030\003 \001(\t\022\024\n\014cl" +
      "osingPrice\030\004 \001(\t\022\024\n\014highestPrice\030\005 \001(\t\022\023" +
      "\n\013lowestPrice\030\006 \001(\t\022\016\n\006volume\030\007 \001(\t\022\016\n\006a" +
      "mount\030\010 \001(\t\022\021\n\twindowEnd\030\t \001(\003Bl\nKcom.so" +
      "lfini.matchengine.liquidity.direct.aiGen" +
      "erated.exchange.mexc.protobufB\031PublicSpo" +
      "tKlineV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicSpotKlineV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicSpotKlineV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicSpotKlineV3Api_descriptor,
        new String[] { "Interval", "WindowStart", "OpeningPrice", "ClosingPrice", "HighestPrice", "LowestPrice", "Volume", "Amount", "WindowEnd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
