// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicMiniTickersV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicMiniTickersV3ApiProto {
  private PublicMiniTickersV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicMiniTickersV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicMiniTickersV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034PublicMiniTickersV3Api.proto\032\033PublicMi" +
      "niTickerV3Api.proto\"?\n\026PublicMiniTickers" +
      "V3Api\022%\n\005items\030\001 \003(\0132\026.PublicMiniTickerV" +
      "3ApiBn\nKcom.solfini.matchengine.liquidit" +
      "y.direct.aiGenerated.exchange.mexc.proto" +
      "bufB\033PublicMiniTickersV3ApiProtoH\001P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicMiniTickerV3ApiProto.getDescriptor(),
        });
    internal_static_PublicMiniTickersV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicMiniTickersV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicMiniTickersV3Api_descriptor,
        new String[] { "Items", });
    PublicMiniTickerV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
