// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerBatchV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicBookTickerBatchV3ApiProto {
  private PublicBookTickerBatchV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicBookTickerBatchV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n PublicBookTickerBatchV3Api.proto\032\033Publ" +
      "icBookTickerV3Api.proto\"C\n\032PublicBookTic" +
      "kerBatchV3Api\022%\n\005items\030\001 \003(\0132\026.PublicBoo" +
      "kTickerV3ApiBr\nKcom.solfini.matchengine." +
      "liquidity.direct.aiGenerated.exchange.me" +
      "xc.protobufB\037PublicBookTickerBatchV3ApiP" +
      "rotoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicBookTickerV3ApiProto.getDescriptor(),
        });
    internal_static_PublicBookTickerBatchV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicBookTickerBatchV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicBookTickerBatchV3Api_descriptor,
        new String[] { "Items", });
    PublicBookTickerV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
