// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicDealsV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public interface PublicDealsV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicDealsV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  java.util.List<PublicDealsV3ApiItem>
      getDealsList();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  PublicDealsV3ApiItem getDeals(int index);
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  int getDealsCount();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  java.util.List<? extends PublicDealsV3ApiItemOrBuilder>
      getDealsOrBuilderList();
  /**
   * <code>repeated .PublicDealsV3ApiItem deals = 1;</code>
   */
  PublicDealsV3ApiItemOrBuilder getDealsOrBuilder(
      int index);

  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  String getEventType();
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();
}
