// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicLimitDepthsV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicLimitDepthsV3ApiProto {
  private PublicLimitDepthsV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicLimitDepthsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicLimitDepthsV3Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicLimitDepthV3ApiItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicLimitDepthV3ApiItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034PublicLimitDepthsV3Api.proto\"\220\001\n\026Publi" +
      "cLimitDepthsV3Api\022(\n\004asks\030\001 \003(\0132\032.Public" +
      "LimitDepthV3ApiItem\022(\n\004bids\030\002 \003(\0132\032.Publ" +
      "icLimitDepthV3ApiItem\022\021\n\teventType\030\003 \001(\t" +
      "\022\017\n\007version\030\004 \001(\t\"<\n\031PublicLimitDepthV3A" +
      "piItem\022\r\n\005price\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\tB" +
      "n\nKcom.solfini.matchengine.liquidity.dir" +
      "ect.aiGenerated.exchange.mexc.protobufB\033" +
      "PublicLimitDepthsV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicLimitDepthsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicLimitDepthsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicLimitDepthsV3Api_descriptor,
        new String[] { "Asks", "Bids", "EventType", "Version", });
    internal_static_PublicLimitDepthV3ApiItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicLimitDepthV3ApiItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicLimitDepthV3ApiItem_descriptor,
        new String[] { "Price", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
