// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicAggreBookTickerV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicAggreBookTickerV3ApiProto {
  private PublicAggreBookTickerV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicAggreBookTickerV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicAggreBookTickerV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n PublicAggreBookTickerV3Api.proto\"j\n\032Pu" +
      "blicAggreBookTickerV3Api\022\020\n\010bidPrice\030\001 \001" +
      "(\t\022\023\n\013bidQuantity\030\002 \001(\t\022\020\n\010askPrice\030\003 \001(" +
      "\t\022\023\n\013askQuantity\030\004 \001(\tBr\nKcom.solfini.ma" +
      "tchengine.liquidity.direct.aiGenerated.e" +
      "xchange.mexc.protobufB\037PublicAggreBookTi" +
      "ckerV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicAggreBookTickerV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicAggreBookTickerV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicAggreBookTickerV3Api_descriptor,
        new String[] { "BidPrice", "BidQuantity", "AskPrice", "AskQuantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
