// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicAggreDealsV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicAggreDealsV3ApiProto {
  private PublicAggreDealsV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicAggreDealsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicAggreDealsV3Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicAggreDealsV3ApiItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033PublicAggreDealsV3Api.proto\"U\n\025PublicA" +
      "ggreDealsV3Api\022)\n\005deals\030\001 \003(\0132\032.PublicAg" +
      "greDealsV3ApiItem\022\021\n\teventType\030\002 \001(\t\"]\n\031" +
      "PublicAggreDealsV3ApiItem\022\r\n\005price\030\001 \001(\t" +
      "\022\020\n\010quantity\030\002 \001(\t\022\021\n\ttradeType\030\003 \001(\005\022\014\n" +
      "\004time\030\004 \001(\003Bm\nKcom.solfini.matchengine.l" +
      "iquidity.direct.aiGenerated.exchange.mex" +
      "c.protobufB\032PublicAggreDealsV3ApiProtoH\001" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicAggreDealsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicAggreDealsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicAggreDealsV3Api_descriptor,
        new String[] { "Deals", "EventType", });
    internal_static_PublicAggreDealsV3ApiItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicAggreDealsV3ApiItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicAggreDealsV3ApiItem_descriptor,
        new String[] { "Price", "Quantity", "TradeType", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
