// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicIncreaseDepthsBatchV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicIncreaseDepthsBatchV3ApiProto {
  private PublicIncreaseDepthsBatchV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicIncreaseDepthsBatchV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicIncreaseDepthsBatchV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$PublicIncreaseDepthsBatchV3Api.proto\032\037" +
      "PublicIncreaseDepthsV3Api.proto\"^\n\036Publi" +
      "cIncreaseDepthsBatchV3Api\022)\n\005items\030\001 \003(\013" +
      "2\032.PublicIncreaseDepthsV3Api\022\021\n\teventTyp" +
      "e\030\002 \001(\tBv\nKcom.solfini.matchengine.liqui" +
      "dity.direct.aiGenerated.exchange.mexc.pr" +
      "otobufB#PublicIncreaseDepthsBatchV3ApiPr" +
      "otoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PublicIncreaseDepthsV3ApiProto.getDescriptor(),
        });
    internal_static_PublicIncreaseDepthsBatchV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicIncreaseDepthsBatchV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicIncreaseDepthsBatchV3Api_descriptor,
        new String[] { "Items", "EventType", });
    PublicIncreaseDepthsV3ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
