// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicDealsV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public interface PublicDealsV3ApiItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicDealsV3ApiItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string price = 1;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <code>string price = 1;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string quantity = 2;</code>
   * @return The quantity.
   */
  String getQuantity();
  /**
   * <code>string quantity = 2;</code>
   * @return The bytes for quantity.
   */
  com.google.protobuf.ByteString
      getQuantityBytes();

  /**
   * <code>int32 tradeType = 3;</code>
   * @return The tradeType.
   */
  int getTradeType();

  /**
   * <code>int64 time = 4;</code>
   * @return The time.
   */
  long getTime();
}
