// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerBatchV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public interface PublicBookTickerBatchV3ApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PublicBookTickerBatchV3Api)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  java.util.List<PublicBookTickerV3Api>
      getItemsList();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  PublicBookTickerV3Api getItems(int index);
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  java.util.List<? extends PublicBookTickerV3ApiOrBuilder>
      getItemsOrBuilderList();
  /**
   * <code>repeated .PublicBookTickerV3Api items = 1;</code>
   */
  PublicBookTickerV3ApiOrBuilder getItemsOrBuilder(
      int index);
}
