// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicDealsV3Api.proto

package com.solfini.matchengine.liquidity.direct.aiGenerated.exchange.mexc.protobuf;

public final class PublicDealsV3ApiProto {
  private PublicDealsV3ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicDealsV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicDealsV3Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicDealsV3ApiItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicDealsV3ApiItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026PublicDealsV3Api.proto\"K\n\020PublicDealsV" +
      "3Api\022$\n\005deals\030\001 \003(\0132\025.PublicDealsV3ApiIt" +
      "em\022\021\n\teventType\030\002 \001(\t\"X\n\024PublicDealsV3Ap" +
      "iItem\022\r\n\005price\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\t\022\021" +
      "\n\ttradeType\030\003 \001(\005\022\014\n\004time\030\004 \001(\003Bh\nKcom.s" +
      "olfini.matchengine.liquidity.direct.aiGe" +
      "nerated.exchange.mexc.protobufB\025PublicDe" +
      "alsV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicDealsV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicDealsV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicDealsV3Api_descriptor,
        new String[] { "Deals", "EventType", });
    internal_static_PublicDealsV3ApiItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicDealsV3ApiItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicDealsV3ApiItem_descriptor,
        new String[] { "Price", "Quantity", "TradeType", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
