CREATE EVENT truncate_tweet_data
ON SCHEDULE EVERY 1 DAY
STARTS '2024-04-08 16:00:00.000'
ON COMPLETION NOT PRESERVE
ENABLE
COMMENT 'Truncate TweetData'
DO DELETE from TweetData WHERE ts <  (now() - INTERVAL 1 YEAR)
