package rnd;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class SnapGen {

  public static void main(String[] args) throws IOException {
    String outputPath = args.length > 0 ? args[0] : "./snap/performance/snap.json";
    try (PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(outputPath)))) {
      writer.print(SECURITY_DEFINITION);
      writer.print(INITIAL_USERS);
      for (int i = 25; i < 1025; i++) {
        writer.println(
            "{\"class\":\"UserAdminMessage\",\"sequenceNumber\":0,\"persistTime\":0,\"sourceSeqNum\":0,\"sourceSendTime\":0,\"snapId\":0,\"kafkaRecordOffset\":0,\"connectionId\":0,\"triggerTimeMillis\":0,\"externalId\":0,\"routeToDestination\":\"ALL\",\"updateType\":1,\"userId\":"
                + i
                + ",\"firmId\":0,\"feeTier\":0,\"requestStatus\":0,\"status\":0,\"accountType\":0,\"lmm\":false,\"marginCurveIdOverride\":0,\"useDiscountFeesCoin\":false,\"isRewardClaimed\":false,\"custodianId\":0,\"userType\":0,\"username\":\"qt_cus_"
                + i + "@yopmail.com\",\"balanceList\":[]}");
      }
      for (int i = 1; i < 1025; i++) {
        if (i >= 22 && i < 25) continue;
        writer.println(
            "{\"class\":\"BalanceAdminMessage\",\"sequenceNumber\":0,\"persistTime\":0,\"sourceSeqNum\":0,\"sourceSendTime\":0,\"snapId\":0,\"kafkaRecordOffset\":0,\"connectionId\":0,\"triggerTimeMillis\":0,\"externalId\":0,\"feeTier\":0,\"requestStatus\":0,\"updateType\":1,\"userId\":"+i+",\"firmId\":0,\"checksum\":0,\"txType\":0,\"txId\":0,\"reference\":0,\"balanceTransferToUserId\":0,\"routeToDestination\":\"null\",\"userType\":0,\"positionArr\":[{\"class\":\"Position\",\"instrumentId\":1,\"quantity\":1000000000000,\"availableQuantity\":1000000000000,\"isTouched\":true,\"assetType\":0,\"usdCostBasis\":0.0,\"usdAvgCostBasis\":0.0,\"usdValue\":1000000000000.00,\"usdUnrealized\":0,\"usdRealized\":10000000000,\"quotedUsdMark\":1.0,\"settleCoinUsdMark\":0.0,\"settleCoinUnrealized\":0.0,\"settleCoinRealized\":0.0,\"bankruptPriceInt\":0,\"markAsReturned\":false},{\"class\":\"Position\",\"instrumentId\":2,\"quantity\":100000000000000,\"availableQuantity\":100000000000000,\"isTouched\":true,\"assetType\":0,\"usdCostBasis\":0.0,\"usdAvgCostBasis\":0.0,\"usdValue\":0,\"usdUnrealized\":0.0,\"usdRealized\":0.0,\"quotedUsdMark\":1500,\"settleCoinUsdMark\":0.0,\"settleCoinUnrealized\":0.0,\"settleCoinRealized\":0.0,\"bankruptPriceInt\":0,\"markAsReturned\":false}]}");
      }
      writer.println(LAST_LINE);
    }
    System.out.println("Snapshot written to " + outputPath);
  }

  private static String SECURITY_DEFINITION = """
      {"class":"SecurityDefinitionAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"updateType":1,"routeToDestination":"ALL","securityId":1,"symbol":"USD","name":"USD","assetType":0,"marketStatus":0,"marketType":0,"baseId":0,"quotedId":0,"priceScale":2,"quantityScale":2,"underlyerId":0,"strikePrice":0,"expireTimeMillis":0,"orderBookStrategy":0,"preOrderCheckStrategy":0,"estimatedUserCount":0,"daysFeedIsActive":0,"estimatedVolatility":0.0,"estimatedVAR":0.0,"settleType":0,"maintMarginPercent":40,"requiredMarginPercent":80,"minQty":0,"maxQty":0,"maxPrice":0,"supportOrderType":0,"marginCurveId":0,"commissionType":0,"indexFeedUsdMark":1.0,"collateralMarginPercentDiscount":0,"arrSize":0,"cacheDepth":0,"textData":"","secondaryOrderId":0,"secondaryExecId":0,"auctionStartTimeHrGMT":0,"auctionDurationTime":0,"auctionFixingAttempts":0,"auctionFixingWaitTime":0,"expireRollTimeMillis":0,"symbolRollCount":0,"physicalSettle":false,"withdrawFee":1.0,"isWithdrawFeePercent":false,"withdrawFeeInstrument":1,"sector":0}
      {"class":"SecurityDefinitionAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"updateType":1,"routeToDestination":"ALL","securityId":2,"symbol":"ETH","name":"ETH","assetType":0,"marketStatus":0,"marketType":0,"baseId":0,"quotedId":0,"priceScale":2,"quantityScale":6,"underlyerId":0,"strikePrice":0,"expireTimeMillis":0,"orderBookStrategy":0,"preOrderCheckStrategy":0,"estimatedUserCount":0,"daysFeedIsActive":0,"estimatedVolatility":0.0,"estimatedVAR":0.0,"settleType":0,"maintMarginPercent":40,"requiredMarginPercent":80,"minQty":0,"maxQty":0,"maxPrice":0,"supportOrderType":0,"marginCurveId":0,"commissionType":0,"indexFeedUsdMark":1638.17,"collateralMarginPercentDiscount":0,"arrSize":0,"cacheDepth":0,"textData":"","secondaryOrderId":0,"secondaryExecId":0,"auctionStartTimeHrGMT":0,"auctionDurationTime":0,"auctionFixingAttempts":0,"auctionFixingWaitTime":0,"expireRollTimeMillis":0,"symbolRollCount":0,"physicalSettle":false,"withdrawFee":0.002,"isWithdrawFeePercent":false,"withdrawFeeInstrument":2,"sector":0}
      {"class":"SecurityDefinitionAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"updateType":1,"routeToDestination":"ALL","securityId":3,"symbol":"ETH/USD","name":"ETH/USD","assetType":1,"marketStatus":0,"marketType":2,"baseId":2,"quotedId":1,"priceScale":2,"quantityScale":6,"underlyerId":0,"strikePrice":0,"expireTimeMillis":0,"orderBookStrategy":2,"preOrderCheckStrategy":11,"estimatedUserCount":0,"daysFeedIsActive":0,"estimatedVolatility":0.0,"estimatedVAR":0.0,"settleType":0,"maintMarginPercent":40,"requiredMarginPercent":80,"minQty":0,"maxQty":0,"maxPrice":0,"supportOrderType":0,"marginCurveId":0,"commissionType":0,"indexFeedUsdMark":1638.17,"collateralMarginPercentDiscount":0,"arrSize":1000000,"cacheDepth":0,"textData":"","secondaryOrderId":7346448386,"secondaryExecId":255074448,"auctionStartTimeHrGMT":0,"auctionDurationTime":0,"auctionFixingAttempts":0,"auctionFixingWaitTime":0,"expireRollTimeMillis":0,"symbolRollCount":0,"physicalSettle":false,"withdrawFee":0.0,"isWithdrawFeePercent":false,"withdrawFeeInstrument":0,"sector":0}
      """;
  private static String INITIAL_USERS = """
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":1,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":0,"username":"chris@bitorderly.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":2,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":0,"username":"rohanw@bitorderly.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":3,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":0,"username":"rohanm@bitorderly.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":4,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":2,"username":"exchange","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":5,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":3,"username":"insurancefund","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":6,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":6,"username":"other","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":8,"firmId":0,"feeTier":10,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":4,"username":"bot","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":9,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":0,"username":"tradeapi","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":10,"firmId":0,"feeTier":3,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":1,"username":"admin","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":11,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":0,"username":"ccc","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":12,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":7,"username":"tokenmanager@bitorderly.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":13,"firmId":0,"feeTier":10,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":1,"userType":4,"username":"mm1@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":14,"firmId":0,"feeTier":10,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":2,"userType":4,"username":"mm2@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":15,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":1,"userType":2,"username":"exchange1@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":16,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":2,"userType":2,"username":"exchange2@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":17,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":1,"userType":3,"username":"insurance1@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":18,"firmId":0,"feeTier":2,"requestStatus":0,"status":0,"accountType":0,"lmm":true,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":0,"userType":5,"username":"test","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":19,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":2,"userType":3,"username":"insurance2@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":20,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":1,"userType":7,"username":"tokenmanager1@bitpaired.com","balanceList":[]}
      {"class":"UserAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":0,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"ALL","updateType":1,"userId":21,"firmId":0,"feeTier":0,"requestStatus":0,"status":0,"accountType":0,"lmm":false,"marginCurveIdOverride":0,"useDiscountFeesCoin":false,"isRewardClaimed":false,"custodianId":2,"userType":7,"username":"tokenmanager2@bitpaired.com","balanceList":[]}
      """;
  private static String LAST_LINE = """
      {"class":"SnapResponseAdminMessage","sequenceNumber":0,"persistTime":0,"sourceSeqNum":0,"sourceSendTime":0,"snapId":1782391204995150316,"kafkaRecordOffset":0,"connectionId":0,"triggerTimeMillis":0,"externalId":0,"routeToDestination":"me01","orderSequenceNumber":0,"inputKafkaRecordOffset":0,"outputKafkaRecordOffset":0,"orderId":0,"execId":0}
      """;
}